EYBlockchain/nightfall_3

- test/http.mjs
- test/neg-http.mjs
- test/utils.mjs
This PR introduces quite a number of structural changes to the tests.
1. **Event driven Tests**. 
This is done by using a queue, `eventLogs`, to track the emission  of `blockProposed` and `Rollback` events. Tests then await the appearance of these events in the queue before progressing to the next set of tests. This makes the test less subject to variation in processing capabilities of the machines running these tests and removes arbitrary waiting.
2. **Arbitrary transactions per block**
An initial foundation to replace the hardcoded 2 transactions per block assumption in both `http` and `neg-http` with a new variable `txPerBlock`  that should match the `TRANSACTIONS_PER_BLOCK` environmental variable used by `optimist`. 
**Note this only currently works yet for `http`.**
~~**This PR is …
> Add event driven tests

- nightfall-deployer/contracts/ChallengesUtil.sol
- nightfall-optimist/src/services/transaction-checker.mjs
While `deposits` do not contain historic roots, there is still a `historicRootBlockNumberL2` field that is emitted with a value of 0 from the on-chain event. 
We should add extra checks and challenges to the "well-formedness"  of `deposit` to ensure that these fields are actually 0. Currently, you are able to change this field to any value while still being considered a valid transaction. 
AFAIK, I cannot think of how this might be exploitable - but it's better to be safe.
@ChaitanyaKonda can you think of any more areas where more checks are needed?
> Check well-formed deposit with historic root

- nightfall-optimist/src/services/database.mjs
- test/neg-http.mjs
This PR adds `blockNumberL2` to the transactions collections. This field is set during `removeTransactionsFromMempool` which is called either when we assemble a block or receive a `blockProposed` event.
`blockNumberL2` is then used during `addTransactionToMemPool`, which is called during a Rollback, to ensure that we do not add transactions that have been included in other blocks as well (i.e. duplicate transactions).
This fixes #94.
> Do not reset rolled back transactions if they are already in another block.

- timber/src/merkle-tree-controller.mjs
- timber/src/routes/merkle-tree.routes.mjs
- timber/src/utils-merkle-tree.mjs
Code to calculate the merkle tree root from a frontier and its corresponding leafIndex.
See here (https://github.com/EYBlockchain/timber/pull/71) for manual postman tests that were run. (Postman tests were used because of familiarity and time constraints).
*Code has not been tested in the context of this monorepo; only in the context of the timber repo*.
Example GET request:
```js
req.body = {
frontier: [0x123abc, 0x234bcd, ... ],
leafIndex: 1234,
}
```
> feat: /calculate-root-from-frontier

- config/default.js
- nightfall-client/package-lock.json
- nightfall-client/package.json
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
- nightfall-optimist/package-lock.json
- nightfall-optimist/package.json
- nightfall-optimist/src/classes/block.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/chain-reorg.mjs
- nightfall-optimist/src/event-handlers/index.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/services/check-block.mjs
- nightfall-optimist/src/services/database.mjs
- nightfall-optimist/src/services/event-buffer.mjs
- test/chain-reorg.mjs
- timber/src/filter-controller.mjs
- timber/src/merkle-tree-controller.mjs
- timber/src/routes/merkle-tree.routes.mjs
- timber/src/utils-merkle-tree.mjs
- timber/src/utils-web3.mjs
This PR pushes some updates that work towards coping with an Ethereum chain reorganisation.  It's not complete but it does already add some potentially useful features that are of interest in themselves. These are:
1) All incoming blockchain events are queued and processed serially in the order that they are received.  This is to prevent async races from changing the order that events are processed in.  Although this has not been an issue to date, it will likely become more of a problem when a chain reorganisation forces extensive re-writes of layer 2 state. For example, new events may be received while outdated layer 2 state is being deleted, and then the new events will be incorrectly removed.
2) A mutex has been added to `findUsableCommitments` calls to stop nightfall-client from …
> Westlad/chain reorg Part 1

- nightfall-optimist/src/event-handlers/new-current-proposer.mjs
- nightfall-optimist/src/services/database.mjs
This PR closes #95.
When a new `changeProposer` event is received, check if we were the last proposer. 
If we are the last proposer, use the on-chain L2 information to reset any transactions that we have included in proposed blocks that did not make it on-chain before the `currentProposer` was rotated away from us.
> Clean up transactions that were proposed in blocks but did not make it on chain

- nightfall-optimist/src/event-handlers/new-current-proposer.mjs
This will fix the current race condition in the proposer handler.
The issue manifests in the test as async block assembler may race the new event queue.
A longer term solution will look to enqueue the block assembler into the event queue as well
> Fix current race condition in handler

- nightfall-deployer/contracts/Proposers.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Stateful.sol
- test/http.mjs
This PR transfers funds collected in `Proposers` and `Shield` to `State` as this is where withdrawals ultimately take place.
In contrast to past conversations, I've changed from low-level calls  to transferring the funds in the `submitTransaction` and `registerProposer` functions directly. 
This has the smallest impact to the existing code base, a lower gas cost than direct `address.call` (~5k gas per call), does not require additional modifiers and doesn't require passing along `msg.sender` for some `registerProposer`.
The only tradeoff is that the `State` contract can now be paid to - which is only a problem if a 'paying' transaction is incorrectly sent to it.
There is also a new test in `http` that checks that the balances in `Shield` and `Proposers` are zero and the funds are now in …
> Move funds to State contract

- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/Proposers.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-optimist/src/routes/proposer.mjs
- test/http.mjs
This closes #98 as well as the comments in that issue.
This PR improves the handling of deregistering proposers:
1. In `deRegisterProposer`, we rotate proposer if the `currentProposer` is being deregistered and now correctly un-splice the deregistering proposer from the linked list.
2. A new `TimeLockedBond` struct is used to hold the bond of deregistering proposers that are waiting out the challenge period.
3. Bonds are now withdrawn using `withdrawBond` that checks that enough time has passed before a withdraw can be processed. A new api endpoint in `optimist` is used to trigger this.
> Improve deregister proposer code

- config/timber.js
- docker-compose.yml
- timber/Dockerfile
- timber/entrypoint.sh
- timber/src/web3.mjs
This fixes a potential race condition where the `timber` come up before the `blockchain1` container. This may cause `timber` to crash as it expects a blockchain provider to be available.
> Add entrypoint script to timber

- docker-compose.geth.yml
- start-nightfall
A small PR that adds a second miner to the Geth private test network.  This will be required for testing chain-reorgs so that we can continue to mine if half of the nodes are paused.
It also adds a `trap` to `./start-nightfall` which ensures any running containers are removed if cntl-c is pressed (or another linux stop signal is received.  Without this, it's possible (but not common) to stop the application but leave containers running, which puts an unnecessary load on ones CPU.
> feat: add another miner, improved start script

- nightfall-client/src/services/commitment-storage.mjs
I recently added a mutex to prevent two concurrent calls to a nightfall-client endpoint both selecting the same commitment before it was marked nullified.  Unfortunately we do not await the `markNullified` promise before releasing the mutex.  This renders the mutex mostly ineffective because another process can run before the markNullified is complete. 
This PR fixes the bug by awaiting to the `markNullified`.
> fix: mutex now awaits markNullified function

- test/http.mjs
- test/neg-http.mjs
This PR makes it so that the tests now work with any number of transactions per block as long as the variables are all set appropriately:
- `txPerBlock` in `http` & `neg-http`
- `TRANSACTIONS_PER_BLOCK` in `docker-compose.yml`
This also closes #55  as the test can be successful run with the above variables set to 32.
> Make tests work with arbitrary tx per blocks

- README.md
The use of the word 'decentralisation' in this context is ambiguous. While the L2 chain **may** have less (although not guaranteed to be) block producers than the Ethereum mainnet, the properties of the optimistic rollup ensure that the network is still trustless.
The key property that on-chain data availability scaling solutions such as `Nightfall_3` have is that it inherits much of the key security and consensus properties from the Ethereum mainnet itself   - as opposed to `Validium-based` or sidechain solutions (which may roll their own).
The documentation is updated to reflect this. Closes #72
> Update wording in readme

- nightfall-client/dropAll.sh
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-optimist/src/event-handlers/rollback.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/database.mjs
- nightfall-optimist/src/services/process-calldata.mjs
- test/neg-http.mjs
This PR fixes a few things:
1. Issues with re-syncing brought about by changes made in `blockPropose` handling.
2. Fixes an issue in client where a duplicate transaction would incorrectly overwrite the `isOnChain` and `isNullifiedOnChain` fields of the initial (non-duplicate) commitment.
3. adds the `STATE` contract for `NewCurrentProposer` listener, `STATE` now emits an event that must be subscribed to.
4. adds a new endpoint (`/mempool`) - will be used in a follow up PR for rollbacks.
5. fixes the delete by `transactionType` which will now correctly delete transfers and withdrawals - previously nothing was being deleted. This change results in a change in `neg-http`.
A separate PR will be submitted for changes to the Rollback methodology.
> Fix resyncing

- nightfall-deployer/contracts/Challenges.sol
- nightfall-optimist/src/routes/block.mjs
- nightfall-optimist/src/services/challenges.mjs
- nightfall-optimist/src/services/database.mjs
Building a challenge for a `duplicateTransaction` uses an unsafe access pattern via `getBlockByTransactionHash` and `findOne`. `findOne` uses an unreliable "natural ordering" to return the blocks and is not suitable if a call might return two items.
The bad block containing the duplicate is saved before this challenge code runs, therefore there will be two blocks in the collection that could be returned from this call. This means there is a 50:50 chance that the wrong block is returned from this call.
In this case, the wrong block is defined as the bad block itself. This would lead to the challenge using the bad block twice as inputs to the on-chain challenge, rather than the bad block and an earlier valid block that contains the first time the duplicate was used.
One of the reasons this …
> Fix duplicateTransactions challenge

- nightfall-optimist/src/event-handlers/challenge-commit.mjs
- nightfall-optimist/src/services/database.mjs
- test/neg-http.mjs
#138 makes use of two optimist instances for the test (although one is just listening). This actually uncovers a bug (unrelated to the PR) in the way that challenger addresses are stored and retrieved.
1.  In `challenge-commit.mjs` the retrieval + check code is not awaited, this causes the `if` condition to always evaluate to true (as promises are not falsy). Therefore, both `optimist` instances considers themselves to be the challenger that sent the on-chain challenge commit. This errors out in the in the second optimist instance.
2. The code in the test needs to be updated since `(await getAccounts())[1]` is actually undefined since the switch from `ganache` deterministic mnemonics to the new specified accounts way. The only reasons tests have worked in the past is likely due to point …
> Fix Challenger storage

- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/index.mjs
- nightfall-client/src/routes/incomingViewingKey.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/src/services/state-sync.mjs
This PR adds functionality for a restarted client instance to perform a re-sync. This enables them to update their local databases based on past events.
It does this using a newly added `blockNumber` that is associated with each commitments <> nullifier pair.  To be safe when re-syncing, we begin scanning the main chain from the smallest `blockNumber` we have stored in our local database. This guarantees we are able to sync events that we may miss that are relevant to us.
This closes #135
> Adds client resync

- nightfall-optimist/src/event-handlers/index.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- nightfall-optimist/src/services/event-queue.mjs
fixes #134 
This PR creates two queues for incoming blockchain events.  Events in the lower priority queue will only be processed if the higher priority queue is empty, otherwise the handler will await the higher priority queue emptying.  The code is generic and more queues can easily be added by putting Queue objects in the `queues` array.
TransactionSubmitted events are placed in the lower priority queue.  All other events are placed in the higher priority queue. To facilitate this, eventHandlers have an associated `priority`, with `priority = 0` being the highest.
The block assembler now monitors the highest priority queue and will only make blocks when it is empty.
> feat: priority queues

- config/default.js
- docker-compose.stubs.yml
- docker-compose.yml
- start-nightfall
fixes #153
This PR tidies up the selection of stubbed circuits by adding another argument to the `./start-nightfall` script.  Now, besides the existing (`-l`, `-h`, `-g`) arguments, you can additionally include `-s` (e.g. `-s -g`).  If you do this, your instance of nightfall will run with stubbed circuit files.  If you miss out `-s` the default behaviour will be to not use stubs.
> feat: use of stubs selectable in startup script

- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
This PR closes #112 and does two things:
1. Adds tracking of claimed block stakes to ensure they can only be claimed once per block.
2. Increases challenger rewards by also crediting the challenger with the sum of all the block stakes from blocks pruned by a successful challenge.
Change (2) seeks to modify the behaviour of the proposers and challengers as follows:
- **Challengers:** Provides a financial incentive to submit fraud proofs even if the bond of a bad proposer has already been claimed. While it may appear that a challenger is incentivised to let blocks be built ontop of a bad block (increasing the potential payout) - they are in a race with other challengers and delaying a challenge submission may result in missing out entirely on a reward.
- **Proposers:** This provides …
> Add block stakes as part of challenge reward

- nightfall-optimist/src/services/challenges.mjs
When a challenge is recognised by a Challenger, a commit to challenge is done first by calling `commitToChallenge` on chain. Only after this is done, do we reveal the challenge on chain. During `commitToChallenge` we save the commitment in Challenger's DB. During reveal the challenge stage, we get this commitment from the database. Incredibly, commitToChallenge tx is received by the blockchain and the event is even received by the event listener in Challenger's optimist before this commitment is even saved in Challenger's DB. We resolved this issue by awaiting the DB write and only after this sending the `commitToChallenge` on chain.
> Race condition between commit challenge and reveal challenge

- challenger
- cli/package-lock.json
- cli/package.json
- cli/src/challenger.mjs
- cli/src/common.mjs
- cli/src/index.mjs
- cli/src/proposer.mjs
- nf
- nightfall-client/src/services/transfer.mjs
- proposer
- zokrates-worker/src/utils/filing.mjs
- zokrates-worker/src/zokrates-lib/extract-vk.mjs
This PR implements a simple but handy command line interface for Nightfall_3.  With it you can exercise all the functions that NF_3 is capable of, in an ad hoc way.  To run it up, start NF_3 as you normally would (e.g. `./start-nightfall -g -s`) then open two terminals:
- In one, run a proposer (`./proposer`).  This will just sit there proposing blocks for you, but otherwise it should stay out of trouble.
- In the other run the cli (`./nf`).  It should be self evident how to use it but be mindful that you have to make enough transactions to fill a Layer 2 block before later transactions can use them as inputs.
If you wish, you can also run the challenger module (`./challenger`) although it will do little at present because you can't use the CLI to make a challengable block.
There are a …
> Command line interface

- nightfall-optimist/src/event-handlers/index.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/services/event-queue.mjs
This PR adds `NewCurrentProposer` handling (and removal) to the internal `optimist` processing queue. It also includes a small refactor of `startEventQueue`.
This is part of a bigger set of refactors enabling #173 and subsequently #139 to be completed.
> Add proposer event handling to queue

- test/http.mjs
As also identified by @LijuJoseJJ , sometimes the tests fail because `commitment/salt` has not yet been stored in the local database before we try to query it.
Here we just wait to ensure the `commitment` variable a value before progressing.
> More robust wait for commitment

- .github/workflows/check-PRs.yml
- common-files/utils/web3.mjs
- config/default.js
- config/timber.js
- docker-compose.testnet.yml
- docker-compose.yml
- nightfall-client/docker-entrypoint.sh
- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/entrypoint.sh
- nightfall-deployer/package-lock.json
- nightfall-deployer/package.json
- nightfall-deployer/src/circuit-setup.mjs
- nightfall-deployer/src/contract-setup.mjs
- nightfall-deployer/truffle-config.js
- nightfall-optimist/docker-entrypoint.sh
- package.json
- start-nightfall
- test/chain-reorg.mjs
- test/http.mjs
- test/neg-http.mjs
- test/tx-gas.mjs
- test/utils.mjs
- timber/entrypoint.sh
- timber/src/auto-start.mjs
- timber/src/web3.mjs
This PR add a github action workflow which will test all PR to master branch by deploying code to infura testnet(ropsten) and run integration test (test/http.mjs and test/neg-http.mjs).
fixes #183 
this PR does few changes to make continues integration works (deploy at ropsten network).
1. lowers `block_stake` and `bond`,  `1 eth` and `10 eth` to `1 wei` and `10 wei` respectively.
2. added basic auth logic to web3 connection by passing `INFURA_PROJECT_SECET` env (this enable a basic security feature as infura set transaction limit per day)
NOTE: Infura testnet deployment `./start-nightfall -t` cannot be tested locally (unless fews changes are made) , because it has dependency on fews secret environment variables
1.  `ETH_PRIVATE_KEY`
2. `INFURA_PROJECT_ID`
3. `INFURA_PROJECT_SECRET` …
> add gtihub workflow to deploy on ropsten testnet and  run integration test

- cli/lib/nf3.mjs
- cli/src/challenger.mjs
- cli/src/index.mjs
- cli/src/liquidity-provider.mjs
- cli/src/proposer.mjs
- common-files/classes/transaction.mjs
- docker-compose.yml
- liquidity-provider
- nightfall-deployer/contracts/Proposers.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-deployer/contracts/Utils.sol
- nightfall-optimist/src/event-handlers/index.mjs
- nightfall-optimist/src/event-handlers/instant-withdrawal.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/routes/transaction.mjs
- nightfall-optimist/src/services/instant-withdrawal.mjs
This is a partial resolution of #177.  It adds instant withdrawals to the SDK (`Nf3 class`). It also fixes a bug in `Nf_3` whereby calls to `Nf3.close` did not shut down open Websockets, and a bug in the off-chain Keccak hash calculation for a Transaction where the proof was not compressed first and, finally, a bug in the on-chain Transaction hash calculation where `compressedSecrets` was not included.  The two methods of hash calculation now agree.
Direct transfers will be added in Pt 2.
To test you have to use the CLI.  There is a new listener which will (uncritically) service all Instant-Withdraw requests.  Run this up with `./liquidity-provider` in a spare window, after you have started nightfall_3 and the `./proposer` listener.  Then you can run the CLI itself (`./nf`). 
To test the …
> Westlad/instant withdrawals  and bug fixes Pt 1

- doc/chain-reorgs.md
fixes #204 
This document explains how NF_3 copes with a chain reorganisation.  Note that the chain-reorganisation code is not yet fully complete; for example, a chain reorg during a L2 rollback is still being worked on, however there are a number of subtleties to adjusting L2 data in response to an L1 chain reorg and this document captures most of that. 
It will be added to as work progresses.
> docs: chain reorg

- common-files/classes/timber.mjs
- config/default.js
- package-lock.json
- package.json
- test/timber.test.mjs
This PR is part of of the eventual solution to #185. Due to the size of the changes when integrating into `optimist`, this PR only contains the core `timber` library and test, and does not replace any existing code in `nightfall_3`. 
The code is extensively documented in a jsdoc style. At a high-level, the `timber` class provides merkle-tree operations (insertion, setMembership, rollbacks) on a timber-like tree (i.e. has a concept of a frontier). 
The tree itself is a recursively defined data structure that only stores leaf values. At each point in the tree, a node is either a `Branch(leftTree, rightTree)` or `Leaf(value)`, where `leftTree` and `rightTree` themselves are either `Branches` or `Leaves`.
Tests are available and can be run using `npx mocha --timeout 0 --bail …
> Create nightfall_3 version of timber

- nightfall-optimist/src/classes/block.mjs
- nightfall-optimist/src/event-handlers/new-current-proposer.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/routes/block.mjs
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- nightfall-optimist/src/services/database.mjs
- nightfall-optimist/src/services/event-queue.mjs
- test/neg-http.mjs
This enqueues the block assembler using the `end` emitter from `queue`. Essentially, we try to enqueue the assembler when the queue is empty.
A few things to note:
- We check the `proposer.isMe` condition in the emitter to fail fast. Otherwise, a non-proposer will constantly try to re-enqueue and eventual consume their memory. We should investigate if long periods of re-enqueueing (i.e. is the proposer just does not have transactions to submit) causes memory issues.
- Note that the `proposer.isMe` check in `block-assembler` is now redundant, however removing that args input will require a bit more re-architecting so I've left it for now.
- I've been able to run the tests without any errors, however i can see the "Out of order block" error happen on multiple consecutive `npm t` runs …
> Enqueue Block Assembler

- .github/workflows/check-PRs.yml
- docker-compose.testnet.yml
- nightfall-deployer/truffle-config.js
- nightfall-optimist/src/routes/block.mjs
- nightfall-optimist/src/services/check-block.mjs
- test/http.mjs
- test/neg-http.mjs
- test/utils.mjs
this fixes #203 
and add github action workflow to deploy and run integration test (env - infura ropsten)
briefing changes and new code added in this PR.
1. added while loop to fetch `getTreeHistoryByCurrentLeafCount()` from `timber` in `optimist`
2. implemented queue with ({ concurrency: 1 }) for transaction coming from optimist via websocket
3. two new function implemented in `http.mjs`, which are `waitForTxExecution()` and `holdupTxQueue()`
waitForTxExecution() :- used in registerProposer and in for loop of deposits,
This function wait/listen for log of event (for deposit `TransactionSubmitted` and for registerProposer its `NewCurrentProposer`)
It fix an error (appears sometimes )`transaction has not mined in 50 blocks` even though nonce to tx are correct (as we have for loop with …
> github acton workflow for Infura ropsten deployment and integration test

- common-files/classes/timber.mjs
- test/timber.test.mjs
Given the size of #241 , this is an interim PR that adds the `statelessSiblingPath` functionality.
This function enables the calculation of a `siblingPath` using only: (1) the frontier, (2) the leafCount, (3) an array of incoming leaves and (4) the leafIndex of the incoming leaves that the siblingPath is for.
We need this functionality as we plan for `client` to not store the commitment tree at all.
This can be tested by running `npx mocha --timeout 0 --bail test/timber.test.mjs` - this will take about 2 mins to finish the run.
> Stateless  sibling paths

- common-files/utils/event-queue.mjs
- nightfall-client/package-lock.json
- nightfall-client/package.json
- nightfall-client/src/event-handlers/index.mjs
- nightfall-client/src/event-handlers/subscribe.mjs
- nightfall-client/src/index.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/routes/block.mjs
This elevates the queue implementation out of `optimist` into `common-files` so it also be used in `client` without duplication.
Note that to do this quickly, we exploit the fact that `common-files` is copied into the `client` and `optimist` during the build. This allows us to keep the `queues` array inside the `event-queue` file (as there is a fresh instantiation in each copy of the `event-queue` file in both `client` and `optimist`).
Long-term we can certainly do better than this and should look at a way to instantiate the `queue` in the `main` files for `optimist` and `client` rather than instantiating in `common-files` and copying it across. This provides some benefits in terms of flexibility on setup (e.g. `client` does not need two queues) and minimises any potential issues with …
> Add queue to client

- doc/chain-reorgs.md
- docker-compose.host.docker.internal.yml
- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/event-handlers/chain-reorg.mjs
- nightfall-client/src/event-handlers/index.mjs
- nightfall-client/src/event-handlers/subscribe.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/chain-reorg.mjs
- nightfall-optimist/src/services/database.mjs
- test/chain-reorg.mjs
- timber/src/filter-controller.mjs
fixes #205 
This PR provides the capability to nightfall-client to cope with a chain reorganisation and to update its L2 database to reflect the new truth of the cannonical chain.  It can currently handle removal of `blockProposed` events by a chain-reorg but not removal of an L2 `rollback` event.  That will be a later PR. 
A new eventHandler has been added that runs when removal of a `blockProposed` event occurs and performs the L2 database updates.  These are actually just resetting information for commitments and nullifications that have been marked as on-chain.  The logic for this approach is discussed [here](https://github.com/EYBlockchain/nightfall_3/blob/westlad/client-reorg/doc/chain-reorgs.md#layer-2-client).
To test, you need to run up the local Geth blockchain, which has the …
> client chain-reorg functionality

- .github/workflows/publish-docker-images.yml
- client.Dockerfile
- deployer.Dockerfile
- docker-compose.images.example.yml
- optimist.Dockerfile
- worker.Dockerfile
This PR adds Dockerfiles copying local dependencies into build images and github actions to push that image to the new github repo, `ghcr.io`. I removed binds where possible, but shared volumes (e.g. `build`, `proving-files`) are still required.
I've already pushed the images manually and created `docker-compose.images.example.yml`, which uses them. If you replace `docker-compose.yml` with this file everything should still work.
Note that the actions file is not tested, however a test run failed on the actions tab of the repo on a previous push. Hopefully it will run on this PR creation...
Closes #273.
> Docker images and release

- common-files/classes/transaction.mjs
This [PR](https://github.com/EYBlockchain/nightfall_3/pull/278) that adds a second historic root has triggered a subtle bug that causes the local calculation of a transaction hash (via `Transaction.calcHash`) does not match the on-chain function `Utils.hashTransaction`.
This is only noticeable now when getting `instant-withdrawals.test` to run as the only time the local and contract values are compared in a test is in this `instant-withdrawal` interaction. 
The issue is that even though `historicRootBlockNumberL2` is of type `uint64[2]`,  the function `encodePacked` will pad any array values (see screenshot from docs) - this seems to be the only time it pads values that are < 32 bytes.  Therefore, locally, we need to change the type to `uint256` for the purposes of calculating the hash.
> Local <> contract transaction hash mismatch

- nightfall-deployer/contracts/Proposers.sol
- nightfall-optimist/src/routes/proposer.mjs
Get proposers endpoint only was always getting one proposer, instead of all proposers. Fix with `nextAddress` property in the loop going one by one proposers in cycle way until the same current proposer again.
In the Proposers.sol contract `nextAddress` was wrong for the current proposer in the case of registering second proposer.
> fix: get proposers collection and register proposer

- cli/lib/nf3.mjs
- cli/lib/tokens.mjs
- nightfall-client/src/routes/commitment.mjs
- nightfall-client/src/services/commitment-storage.mjs
Create functionality in the SDK to provide the detailed information about tokenIds in ERC721 and ERC1155 tokens in L2.
- `getLayer2BalancesDetails(ercList)` where you can pass a list of ERC contract addresses to filter. If you don't pass parameters it doesn't filter and return all the ERC contracts balance.
```
const balances = await nf3User1.getLayer2BalancesDetails(['0x103ac4b398bca487df8b27fd484549e33c234b0d']);
```
Example where the first address is an ERC20 and the second is ERC721 with 2 tokenIds.
```
{
'0xb5acbe9a0f1f8b98f3fc04471f7fe5d2c222cb44': [ { balance: 60, tokenId: 0 } ],
'0x103ac4b398bca487df8b27fd484549e33c234b0d': [ { balance: 1, tokenId: 1 }, { balance: 1, tokenId: 2 } ]
}
```
> Balance L2 tokens non ERC20 in SDK

- common-files/utils/event-queue.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/new-current-proposer.mjs
- nightfall-optimist/src/event-handlers/rollback.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- nightfall-optimist/src/services/database.mjs
- test/neg-http.mjs
- test/rollback-resync.test.mjs
This PR closes #139 and #266. These are combined as a single PR because the former will not past tests without the latter. This is not due to the PR itself but the way that `neg-http` is written - leaving the database in a non-valid state causes unintended errors.
1) To prevent the block-assembler from running, we introduce a new queue (`stopQueue`). This is a manual queue so does not automatically run queued jobs.  Before running the `block-assembler`, not only do we check that the `stateQueue` (i.e. queue[0]) is empty - but also that there is nothing queued in the `stopQueue`.
Elements are enqueued into `stopQueue` when a bad block is detected in the `blockProposeHandler`. Finally, they are dequeued at the completion of `rollbackHandler`.
2) To clean up the proposer, we modify …
> Stop Proposing on top of bad blocks and clean up on proposer rotation

- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/services/commitment-storage.mjs
This PR closes #360.
Previously, we used commitments to decide if we should store block and transaction information of transactions we care about in `client`. However, when a withdrawal transaction is made - it does not have commitments. Therefore, we do not store it when we should. 
This PR changes this behaviour so that we use `transactionHash` to decide if we should store a block and its transactions.
This can be tested in the following way (you may need to rebuild containers and purge volumes if you are from master): 
1. Fetch `daveroga/test-bug-instant-withdraw` and `./start-nightfall` - stubs circuits can be used.
2. Run `npm run test-e2e`, which should fail at `should allow instant withdraw of existing withdraw`.
3. Cherry-pick this commit onto the branch using `git cherry-pick …
> Use Transaction Hash when deciding if client should save blocks

- docker-compose.yml
- wallet/docker-entry.sh
- wallet/test/tx_test.py
When a block is submitted, now clients may wait up to 12 blocks for confirmation. This has an impact on wallet transaction tests, which expected results much earlier. 
Additionally, i have seen that when launching `./start-nightfall -wt -s` (running wallet tests), nightfall-client used to timed out waiting for some contract to be deployed. I have increased RETRIEs from 50 to 80.
Also, i have seen that wallet tests could start before all contracts were deployed. I have added a new synchronization mechanism to prevent this from happening.
Finally, in order to provide simpler debugging with wallet tests, i now display information about proposer and liquidity provider.
> Increased timings 

- .github/workflows/check-PRs.yml
- .github/workflows/publish-docker-images.yml
- nightfall-optimist/Dockerfile
- optimist.Dockerfile
- setup-nightfall
- worker.Dockerfile
- zokrates-worker/Dockerfile
- zokrates.Dockerfile
This tweak builds a separate zokrates container image, from which optimist and worker copy the zokrates binary. That means we only compile zokrates once, which saves about 10 mins of build time on PR #404
> faster zokrates build

- wallet/src/views/wallet/index.jsx
We need the metamask signature as part of the passphrase for the mnemonic.
However, we should not pre-emptively show the generate mnemonic modal when the signing is waiting for user confirmation.
This fix checks if there exists an encrypted mnemonic in localStorage associated with this metamask account before showing the modal.
> Check if mnemonic exists before pop up

- wallet/src/views/wallet/index.jsx
this PR fixes a small, bug I create(may be), when wallet page is refreshed token balance is not parsed
> (nightfall-browser) bug fix on wallet page reload

- nightfall-deployer/contracts/ChallengesUtil.sol
This fixes #424 
Good blocks were successfully challenged previously because of the length checks in libChallengeTransactionType() . 
Fixing the transaction type checks in contract accordingly.
> fix: remove length check in invalid txn typecheck

- nightfall-deployer/contracts/Proposers.sol
- test/http.mjs
- test/neg-http.mjs
fixes #494.
Currently, a proposer can register twice.  This causes the circular linked-list of proposers to break and the proposer registering twice then becomes the only proposer.  This PR fixes that bug by simply reverting if `registerProposer` is called with a pre-existing proposer address.
How to test:  A test case has been added to `http.mjs` and so this PR is tested by the normal CI tests.
> bug - proposers can register twice

- nightfall-client/src/services/transfer.mjs
- nightfall-deployer/circuits/double_transfer.zok
- nightfall-deployer/circuits/double_transfer_stub.zok
- nightfall-deployer/circuits/single_transfer.zok
- nightfall-deployer/circuits/single_transfer_stub.zok
- nightfall-optimist/src/services/transaction-checker.mjs
fixes #497
This fixes a bug whereby transfer transactions advertise the ERCAddress of the token being transferred.  Allowing this would greatly reduce the size of the annonymity set, and it's unnecessary because the Shield contract doesn't need to know it. Hence we make ERCAddress a private variable in the ZKP circuit.
To test: testing is the conventional `./start-nightfall -g [-s]`, `npm t` approach *BUT* because the circuits have changed, you must delete your `proving_files` volume to force a new trusted setup and to start using the new circuits. 
When the test has run, and before you stop nightfall, you can do `docker-compose logs | grep -A 4 'transactionType": "1"'` to see the single transfer transactions and the ERCAddress contained therein (should be zeroed out).  Replace "1" with …
> remove ERC addresses from transfer

- wallet/.env
- wallet/package.json
- wallet/src/components/BridgeComponent/index.tsx
- wallet/src/components/TokenItem/index.jsx
- wallet/src/hooks/User/index.jsx
- wallet/src/nightfall-browser/event-handlers/block-proposed.js
- wallet/src/nightfall-browser/services/commitment-storage.js
- wallet/src/nightfall-browser/services/database.js
- wallet/src/nightfall-browser/services/withdraw.js
- wallet/src/utils/lib/local-storage.js
- wallet/src/views/wallet/index.jsx
- wallet/tests/e2e/specs/e2e-spec.js
This closes #538 and #522 as well as adds off chain transfers to **Send** (by default) and **Withdraw** (by selection).
Timber now syncs by retrieving trees from explicit blockNumberL2 rather than `getLatestTree` which is a non-idempotent operation.
> Offchain transfers + sync + stored pkd

- .github/workflows/browser-e2e-test.yml
- wallet/package.json
with synpress we cannot import 'config' module and use config from there.
I will keep trying some other way to pass config in subsequent PR on e2e test
> (nightfall-browser) update e2e-test run on generic ENV

- wallet/src/hooks/User/index.jsx
The array of objects received from the `sync` endpoint is incorrectly accessed. The `blockNumberL2` field is within the `block` field.
> Missing `.block` when accessing historical blocks.

- .github/workflows/browser-e2e-test.yml
- wallet/README.md
- wallet/src/nightfall-browser/services/withdraw.js
This PR comment out github actions workflow which test browser e2e test, for two reason.
1.  currently in master browser e2e test are broken because significant change in UI.
2. since we are tight with deliverable it is getting bit tedious to keep changing e2e test workflow with change in code.
Understanding is, later this will be reverted back
> remove browser e2e test GitHub actions workflow

- .eslintignore
- wallet/package-lock.json
- wallet/package.json
- wallet/src/common-files/classes/bigFloat.ts
- wallet/src/common-files/classes/transaction.js
- wallet/src/components/BridgeComponent/index.jsx
- wallet/src/components/Input/index.tsx
- wallet/src/components/Input/masks.ts
- wallet/src/components/Modals/sendModal.tsx
- wallet/src/contract-abis/Shield.json
- wallet/src/hooks/Account/index.tsx
- wallet/src/nightfall-browser/services/commitment-storage.js
- wallet/tests/unit/float.ts
- wallet/tsconfig.json
This PR adds functionality for the browser to be able to handle uint112 values. It does this primarily through updating the browser to use `bigInts` where possible and the use of a new `BigFloat` class. 
This class  acts like `bigInt` but for floating points. It is not arbitrary precision, but instead fixed precision where the significand (the part on the LHS of the decimal) is a `bigInt`. Floating points are required because of the necessary UI conversions to display values to the user.
This class currently only supports addition and multiplication - since that is all the browser needs for now.
Note: There are also smaller eslint fixes in this PR.
- The `BigFloat` class can be tested using `npm t` **inside the wallet directory**
> Handle Uint112 in browser

- doc/upgrading-contracts.md
This PR adds documentation about upgrading contracts, which was missed from the original PR.
> docs: adding contract upgrade document

- .eslintignore
- common-files/classes/transaction.mjs
- config/default.js
- nightfall-deployer/contracts/Structures.sol
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/transaction-checker.mjs
- wallet/package-lock.json
- wallet/package.json
- wallet/src/common-files/classes/bigFloat.ts
- wallet/src/common-files/classes/transaction.js
- wallet/src/components/BridgeComponent/index.jsx
- wallet/src/components/Input/index.tsx
- wallet/src/components/Input/masks.ts
- wallet/src/components/Modals/sendModal.tsx
- wallet/src/contract-abis/Shield.json
- wallet/src/hooks/Account/index.tsx
- wallet/src/nightfall-browser/services/commitment-storage.js
- wallet/src/nightfall-browser/services/withdraw.js
- wallet/tests/unit/float.ts
- wallet/tsconfig.json
This PR fixes #607.  It changes the dynamic range of a L2 transaction value to 112 bits, which can accommodate 18 decimal places with a 10^15 max value. The current 64 bit value is too small
> 112 bit transaction value to enable full 18 decimal place range with large integer part

- wallet/src/components/BridgeComponent/index.jsx
- wallet/src/components/Input/index.tsx
- wallet/src/components/Input/masks.ts
- wallet/src/components/Modals/sendModal.tsx
- wallet/src/hooks/Account/index.tsx
This PR just prevents users from inputting more than 4 decimals as a transfer value.
This isn't because we cannot handle more - but it's a way to mitigate a user doing something silly, e.g. adding more decimal places than is supported by the token's ERC20 contract.
- `npm ci`
- `nom run start`
- when using the browser, try to input more than 4 decimals in the Bridge or Send areas.
> Limit input in Bridge and Send to 4 decimals

- wallet/src/common-files/utils/contract.js
- wallet/src/components/Input/index.tsx
- wallet/src/components/Input/masks.ts
- wallet/src/hooks/Account/index.tsx
This PR adds better gas estimation for any on-chain calls in the browser. It primarily uses etherscan's estimation api (this is wrapped behind a simple AWS gateway), but has a fallback function that uses the local node to do so.
The advantage of the etherscan api is that it has a richer estimation algorithm (with low, med and high - we use medium for this application) while the fallback relies on the average gas cost of the last **n**  blocks.
The url endpoint is hardcoded, it will be used for all deployments of the wallet (i.e. `testnet`, `mainnet`) since etherscan only provides an estimation for `mainnet`. This isn't a problem as it means we get a good idea of the gas costs involved on mainnet even while testing using `Goerli`.
Placing the api behind an AWS endpoint means we can monitor …
> Better Gas estimation for on-chain calls

- config/default.js
- nightfall-client/src/classes/commitment.mjs
- nightfall-client/src/classes/nullifier.mjs
- nightfall-client/src/services/transfer.mjs
- nightfall-deployer/circuits/double_transfer.zok
- nightfall-deployer/circuits/double_transfer_stub.zok
- nightfall-deployer/circuits/single_transfer.zok
- nightfall-deployer/circuits/single_transfer_stub.zok
- nightfall-deployer/circuits/withdraw.zok
- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/ChallengesUtil.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Verifier.sol
- nightfall-optimist/src/services/transaction-checker.mjs
- wallet/src/nightfall-browser/classes/commitment.js
- wallet/src/nightfall-browser/classes/nullifier.js
_NB:  To test this, you will need to delete your proving_files volume so that new keys are created. `docker compose down -v` will do this.  Also, test without stubs because the circuits are changed, thus a stubbed test is inadequate._
The nullifier is truncated to 31 bytes to prevent overflow but this truncation is not checked.  This means that new nullifiers can be created by adding high-order bits to the nullifier, even without exceeding the modulus.
This PR fixes that by requiring the higher-order byte of the nullifier is zero.  If not, a challenge is raised.  This is slightly more efficient than including the check in the circuit, which would make the proof bigger but requires less code.
We also need to produce nullifier hashes with a zero higher order byte so that we don't fail our …
> overflow checks

- doc/wallet-privacy.md
This PR is purely an addition to the documentation.  It explains how to maintain privacy when using the polygon-nightfall wallet.
> docs: information on maintaining privacy

- cli/lib/nf3.mjs
- nightfall-optimist/src/routes/block.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- test/e2e/tokens/erc1155.test.mjs
This PR creates a new `optimist` endpoint `/block/make-now` (and wrappers it in the Nf3 class method `makeBlockNow`).  When called, `optimist` will make a 'short' block using whatever transactions it has in its database, even if that is less than `TRANSACTIONS_PER_BLOCK`. The short block is still made by queuing `conditionalMakeBlock` in the usual way, so the queue is never bypassed. The new code will not make a block if there are no transactions: there must be at least one. If there are already >=`TRANSACTIONS_PER_BLOCK` transactions, then calling this endpoint has no effect.
To test, an additional test stanza has been added to the ERC1155 tests, whereby `makeBlockNow` is called and a single deposit transaction is made.  The test then waits for a block to be created.  Normally it would …
> blocks can be made at any point in time

- config/default.js
- nightfall-deployer/migrations/2_deploy_upgradeable.js
- nightfall-deployer/migrations/3_test_tokens_migration.js
- test/e2e/tokens/erc20.test.mjs
This PR extends the test code that put restrictions on the amount that can be deposited or withdrawn.
It selects the contract addresses to put limits on via the environment variable `ETH_NETWORK` which is the same one used to select the truffle configuration for deployment, so it's transparent to the deployer.  Value restrictions are created in the contract migration.
Test in the normal way, although obviously it's not possible to directly test mainnet and goerli values.  However the symmetry between those and the ganache (`ETH_NETWORK=blockchain1`) case.
> add amount restrictions for mainnet and goerli ERC contracts

- wallet/package-lock.json
- wallet/src/common-files/utils/contract.js
- wallet/src/components/BridgeComponent/index.jsx
- wallet/src/web-worker/index.js
- wallet/tsconfig.json
This PR fixes a few small bugs discovered due pre-prod deployment.
1. Wallet submitTransaction: Setting a `msg.value` in the transaction to `Shield.submitTransaction` sets a previously zero state in the `feeBook`. This additional gas requirement is not detected in the `estimateGas` function. As a result, the gasLimit is too low sometimes (we attempted to minimise this using a 10% buffer - this is now increased to 50%). 
2. UI in bridge page wasn't correctly being formatted because we were incorrectly mixing between string and bigInt types.
3. The use of `global.config` in the web worker breaks in production deployment (but not in local development). This is likely due to a difference in the `webpack build` vs `webpack dev server` environments.
> Small Wallet Bugs

- .eslintignore
- common-files/utils/crypto/multihash.mjs
- nightfall-deployer/migrations/2_deploy_upgradeable.js
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/services/state-sync.mjs
This PR will cause any transactions that appear in a L2 block which `optimist` has not got in its database, to be saved. 
This can happen when `optimist` is being resynced because the process only saves transactions that are received as part of a TransactionSubmitted event; offchain events do not create these.
I have not yet created a positive test for this code.  This will follow.
> Save external offchain transactions in optimist

- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
- test/e2e/tokens/erc20.test.mjs
The offchain transfer tests in `erc20.test.mjs` were evergreen; `client` was unable to connect to `optimist`'s `/proposer/offchain-transaction` endpoint because no `optimist` API URL was provided by the test harness to `client`.  This caused a connection error when `client` tried to connect.  However the error was thrown and caught inside an async `.forEach` loop inside `transfer.mjs` and so did not propagate back to the test harness - a double whammy.
This PR fixes both problems by providing a correct URL for `optimist` (NB: this has to be the URL as seen from inside the `client` container), and by propagating any error correctly by turning the `.forEach` into a `.map` then awaiting completion of the calls to `optimist`.
> fix offchain connection and tests

- common-files/utils/event-queue.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/database.mjs
- nightfall-optimist/src/services/state-sync.mjs
- package.json
This fixes a number of corner-case syncing issues:
1) When optimist synchronises, it's possible that new transactions could come in.  These were ignored.  To fix this, we subscribe to events from the L1 block one after syncing ends, rather than from the current block, which may be ahead by some distance.
2) offchain transactions are now queued along with onchain ones.  This gives a consistent way of managing them during synchronisation (and more generally).
3) When syncing, the block and transaction queues are paused.  They will still accept new transactions but these are not processed until syncing is finished.
> fix more syncing issues

- nightfall-deployer/contracts/Shield.sol
Critical bug detected by the Nightfall audit.
A proposer could call repeatedly the function `requestBlockPayment` in the Shield contract for the same block and will add BLOCK_STAKE to his pending withdrawal each time.  
Adding ` state.setBlockStakeWithdrawn(blockHash)` at the end of the function fixes this bug as it's checked in the function that the block stake is not already withdrawn for the blocHash.
```
require(
state.isBlockStakeWithdrawn(blockHash) == false,
'The block stake for this block is already claimed'
);
```
> Fix: Mark block stake as withdrawn for the block

- nightfall-deployer/contracts/Shield.sol
It's generally good/safe behaviour to ensure that if a `require` check passes, that we immediately resolve the state effects before performing any interaction. 
This PR applies to two areas:
1. `advanceWithdrawal`: Prevents re-entrancy on `transferFrom`. This isn't really an attack since if `currentOwner` is set to a malicious contract that re-enters,  `msg.sender` will reference the contract and the attacker will cycle their funds. Nevertheless, we are modifying this to be safe.
2. `requestBlockPayment`: I don't think this is easily re-entrant, but just modifying it for safety.
> Apply check-effect-interaction pattern to contract.

- cli/lib/constants.mjs
- cli/lib/nf3.mjs
PR enables to have a configurable GAS_MULTIPLIER factor. By default, value is 2, but can be overwritten by declaring ENV `GAS_MULTIPLIER`
> Configurable gas_multiplier

- test/ping-pong/user-local/src/index.mjs
During ping pong test in Goerli, i find that `deposit` may fail for different reasons (most likely is a timeout). I now catch this condition so that test can continue if we want.
> capture timeouts in deposit

- nightfall-optimist/src/event-handlers/block-proposed.mjs
> blocknumberL2 -> blockNumberL2

- wallet/src/components/BridgeComponent/index.jsx
Wrong selected token - MATIC tx. From Nightfall Assets click `Deposit` or `Withdraw` button next to MATIC. Selected token on L2 Bridge defaults to ETH (`supportedTokens[0]`) since `t.address` in _supported-tokens-testnet.ts_ is not lower case.
> fix: initialToken couldnt find MATIC due to lowerCase method

- wallet/src/components/BridgeComponent/index.jsx
- wallet/src/components/BridgeComponent/styles.scss
- wallet/src/components/Modals/Bridge/Transfer/index.jsx
- wallet/src/components/Modals/sendModal.tsx
Small PR that adds a margin to the right of `Transfer Mode: ` text and fixes a couple of typos.
> fix: margin, typos

- nightfall-deployer/contracts/ERCInterface.sol
- nightfall-deployer/contracts/Shield.sol
This PR provides the deployer of the contract the capability to transfer the balance of the shield contract to their address as requested by Polygon. This is meant to be only used in the event of an attack during which this could be used to save funds in shield contract. This will later be moved into the control of a DAO or be removed after sufficient testing on mainnet and security audit.
Only the address (called owner address here) that deploys the Shield contract can transfer the funds to itself by calling `transferShieldBalance(address ercAddress, uint256 value)`. If the value is 0, then the entire balance for that token will be transferred.
Test: 
- Copy the below specified code in `nightfall-deployer/migrations/3_test_tokens_migration.js` at Line 36
- Then run `./start-nightfall -g …
> feat: adding transferShieldBalance

- cli/lib/constants.mjs
- cli/lib/nf3.mjs
- config/default.js
- nightfall-client/src/services/state-sync.mjs
- nightfall-deployer/package-lock.json
- nightfall-deployer/package.json
- nightfall-deployer/truffle-config.js
- test/ping-pong/user-local/src/index.mjs
Changes deployed to mainnet:
- nf3 : 
-  Configurable` GAS / GAS_PRICE 
- client : 
- Add STATE_GENESIS_BLOCK to speed syncrhonization
- deployer: 
- truffle 5.5.13
- configurable gas via ENV
- ping-pong
- Allow different test length to mainnet environment
> nightfall mainnet deployment

- cli/lib/constants.mjs
- cli/lib/nf3.mjs
fixes #666 
The proposer uses the nf3 class to submit transactions.  The way that this set the gasPrice and gasLimit was quite crude and results in the proposer paying over the odds for gas and using such a high gas limit that there is not enough in the proposer's account to submit the transaction.  This PR fixes that and gives much better values for both.  The strategy used is essentially the same as for the wallet.
For gasPrice:
- it uses Etherescan to get an average value for the last several block.  If that fails...
- it uses web3js to find the gasPrice for the previous block,  If that fails...
- it uses a fixed value (set at 100 GWei, currently).
In each case, the resulting figure is multiplied by a fixed multiplier (`GAS_PRICE_MULTIPLIER`) to give high confidence of a successful …
> Better estimating of proposer gas price and gas limit

- common-files/utils/event-queue.mjs
- nightfall-client/src/services/state-sync.mjs
- nightfall-optimist/src/event-handlers/subscribe.mjs
- nightfall-optimist/src/index.mjs
- nightfall-optimist/src/services/state-sync.mjs
Currently,  when we restart optimist, it will resync before it starts listening to events. It: pauses processing of its input queues; replays all existing transactions; restarts processing its queues; subscribes to new events from the point of the last L2 block in its freshly-resynced database.
This can cause errors to display because any transactions which arrived after the last L2 block are played twice.  Optimist will drop the second event, so no harm is done, but it will show an error in the logs.
Additionally, this process is overly complex: we stop processing events in the queues while resyncing.  This means we could simply start our event listeners as our first action;  they won't hurt the resync because any events they hear will just join the queue and wait until the resync is …
> resync cleanup

- test/e2e/tokens/erc20.test.mjs
There is a race condition problem where a transfer needed commitment from prior transaction which has not been written to the client’s database yet. Adding some waiting time solves it. So it is just the test and not the functionality of restricted withdrawals that is broken
> fix: erc20 test race condition

- nightfall-deployer/migrations/2_deploy_upgradeable.js
We deploy `Structures.sol` and `Config.sol` but it's unnecessary.  These contracts are inherited by several other contracts but they're never called by anything.
> remove unnecessary deploys

- .github/wip.yml
- .github/workflows/check-PRs.yml
Adds a dependency-check to Github Action which verifies for vulnerabilities on dependencies and enables the use of WIP (Work in Progress) into PR titles.
> #ZH-3 - Applying small improvements to Github and Actions

- wallet/src/components/TokenItem/index.jsx
- wallet/src/components/Transactions/index.jsx
The gas calculation has already been fixed previously:
line: 255 file: wallet/src/components/BridgeComponent/index.jsx
line: 289 file: wallet/src/components/BridgeComponent/index.jsx
In this pr the calculation of the amounts displayed in the wallet was changed, using bigint and bigfloat, making it consistent with the gas calculation
> Value calculation with bigint and bigfloat

- common-files/utils/crypto/number-theory.mjs
- nightfall-client/src/utils/crypto/encryption/elgamal.mjs
- nightfall-client/src/utils/crypto/encryption/elligator2.mjs
This PR closes [#147](https://github.com/EYBlockchain/nightfall_3_private/issues/147) adds some safe modulo operations where they have been missing.
> Addressing audit Issue Y

- nightfall-deployer/contracts/Utils.sol
This fixes [issue J](https://github.com/EYBlockchain/nightfall_3_private/issues/132).  It's a simple fix to constrain two array lengths to the length of the data they contain.
> Issue J: public input array lengths

- nightfall-client/README.md
- nightfall-client/start-client
Remove `-d` option in start-client and always run as dev mode building the client from the nightfall-client files of the local repository.
> Remove dev option in start-client

- test/e2e/gas.test.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
Changed time jump from 3600 * 24 * 10 seconds to 3600 * 24 * 50 seconds, as the comment suggests a time jump of 50 days.
> fix: Changing incorrect comment from '50 days' to '10 days'

- nightfall-optimist/start-optimist.sh
Synchronizer did not work with testnet. This PR fixes this
> optimist syncing with testnet

- nightfall-client/README.md
- nightfall-client/start-client
- nightfall-optimist/src/services/database.mjs
- test/e2e/gas.test.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
Issue #574 
Added to the `deleteTreeByBlockNumberL2` function, the ability to update the block by setting `rollback = true`, so as to trigger the change stream, wait for a small delay and then delete the block.
> Delete and update operations in blocks collection #574

- nightfall-deployer/contracts/ChallengesUtil.sol
The function libChallengeNullifier performs a duplicate nullifier challenge to prevent double spending by challenging two duplicate nullifiers from two different transactions. If either of the two transactions has a zero nullifier, which is valid for some types of transactions, the challenge would still pass. The proposer is slashed and the challenger is rewarded for an invalid challenge.
Solution:
Added a check to verify that either one of the nullifiers is non-zero:
require(tx1.nullifiers[nullifierIndex1]!=0 && tx1.nullifiers[nullifierIndex1] == tx2.nullifiers[nullifierIndex2],'Not matching nullifiers')
> Invalid Duplicate Nullifier Challenge Can Pass

- config/default.js
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/services/database.mjs
- package.json
- test/adversary.test.mjs
Fixes: #813 
We will store information about invalid blocks in optimist and the type of challenge they generate:
- Created collection `invalid_blocks` in optimist.
- `invalid_blocks` will store this information when an invalid block is detected:
- invalidCode
- invalidMessage
- block data
- Fixed adversary test check balances when calling `npm run adversary-test-all`
> Save invalid blocks in optimist database

- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/src/services/commitment-sync.mjs
- wallet/src/nightfall-browser/event-handlers/block-proposed.js
this PR for now fixes wallet/browser and nightfall_client
- only storing relevant transaction
- also only storing block object for which any transaction is stored to db
fixes #667
> avoid storing redundant tx from blockpropose event

- config/default.js
- wallet/src/nightfall-browser/services/fetch-circuit.js
- wallet/src/static/supported-token-lists/supported-tokens-local.ts
- wallet/src/web-worker/index.js
This PR refactors wallet app by redundant code for circuits files
> refactor aws circuits path in config

- nightfall-client/src/services/commitment-storage.mjs
Fix #836 
When double transfer value matches sum of both commitments, there is a 500 error. This PR fixes that and returns `null` (No commitments found).
> correctly handle error produced when double transfer matches sum of commitments' values

- nightfall-administrator/src/services/contract-transactions.mjs
- nightfall-administrator/src/services/helpers.mjs
- nightfall-administrator/src/ui/get-info.mjs
- nightfall-administrator/src/ui/menu.mjs
- nightfall-deployer/contracts/Shield.sol
fixes #835 
This PR removes the ability to transfer funds from the Shield escrow pools. It's no longer required as withdrawals can be paused in the event of an emergency.
It also fixes a bug in the administrator container whereby actions that required more than one function call to the blockchain were not correctly handled.
There is no specific test for the removal of the transfer function (because it was not tested in any case).  The normal test suite suffices.  To test the administrator function, refer to the instructions [here](https://github.com/EYBlockchain/nightfall_3/blob/westlad/escrow-removal/nightfall-administrator/README.md)
> remove escrow transfer function and admin bugfix

- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
This PR addresses a small fix found in the SDK related to ercAddress comparison. To avoid mistakes, both maticAddress and ercAddress are converted to lower case
> ErcAddress and fee address check 

- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
This PR solves #803 and implements `makeBlockNow` function for the circuits tests. 
The ganache test run time is reduced by approximately a 40%. 
In addition, tests are can be run now independently (so we can use .skip to only test specific tests). However, I'd strongly suggest modifying even more the tests so that the commitments are deleted afterEach test. This would completely decouple each test and will help to test new circuit features more easily.
> refactor: updating tests to use make block now

- setup-nightfall
Adding `no-cache` flag when running `setupNightfall.sh`.
> Mac workaround for NF setup

- nightfall-deployer/contracts/MerkleTree_Stateless.sol
When the node index is even, we need to hash the frontier slot with `nodeValue` not with 0 (that is only when the node index is odd).
> Incorrect right-sibling hash

- apps/proposer/src/routes/proposer.mjs
- cli/lib/nf3.mjs
Fixes: #877 
We need to add mempool endpoint in the proposer for the block explorer to know information about pending transactions.
- `proposer/mempool` endpoint created in proposer that calls existing `proposer/mempool` from optimist.
> Block Explorer: add mempool endpoint in the proposer

- config/default.js
- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Utils.sol
- nightfall-optimist/src/classes/block.mjs
- wallet/src/nightfall-browser/event-handlers/block-proposed.js
Currently, each block contains a merkle tree of height 5 (32 leaves) no matter the actual number of transactions contained. This PR modifies that so the transactions' merkle tree will have a variable height depending on the number of transactions. If a block contains 12 transactions, a merkle tree of height 4 will be used. 
The block will still be limited to 32 transactions by the TRANSACTIONS_PER_BLOCK parameter. This PR will allow increase / decrease that number by only modifying that config parameter in the default.js and Config.sol with no further modifications to the code.
> Variable height merkle trees for transactions

- README.md
- docker-compose.apps.yml
- proposer.Dockerfile
- start-apps
This PR proposes that the proposer (pun intended) is containerized so all its paths match with our deployment repo. A new script is born that simply runs this new `docker-compose` file
> Containerizing proposer

- nightfall-deployer/src/contract-setup.mjs
Fix: #949 
When deploying in the infra the ownership of the contracts is not being transferred to the multisig contract address.
> Fix multisig contracts ownership

- .github/workflows/check-PRs.yml
This PR disables the adversary test because it isn't working in a consistent way at the moment. It will be re-enabled when this issue is solved.
> Disabling adversary test

- config/default.js
- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
- nightfall-client/src/utils/computeCircuitInputs.mjs
- nightfall-deployer/circuits/common/generic_circuit/Stubs/nullifiers_stub.zok
- nightfall-deployer/circuits/common/generic_circuit/Verifiers/verify_nullifiers.zok
- nightfall-deployer/circuits/common/utils/calculateKeys.zok
- nightfall-deployer/circuits/common/utils/structures.zok
- nightfall-deployer/circuits/transfer.zok
- nightfall-deployer/circuits/transfer_stub.zok
- nightfall-deployer/circuits/withdraw.zok
- nightfall-deployer/circuits/withdraw_stub.zok
- wallet/src/nightfall-browser/services/transfer.js
- wallet/src/nightfall-browser/services/withdraw.js
- wallet/src/nightfall-browser/utils/compute-witness.ts
This PR modifies the nullifier struct in the circuits so that rootKey is only sent once and therefore the nullifierKey and zkpPublicKey are calculated only once. With this change, the transfer and withdrawal circuits have a constraint reduction of around 12K, which is roughly a 20% reduction
Yes, it closes #978 
No
No
> Modifying Nullifier Struct in the circuits

- common-files/utils/contract.mjs
- nightfall-client/src/app.mjs
- nightfall-client/src/routes/contract-abi.mjs
- nightfall-client/src/routes/index.mjs
- nightfall-optimist/src/app.mjs
- nightfall-optimist/src/routes/contract-abi.mjs
- nightfall-optimist/src/routes/index.mjs
Fix: #990
We have some issues when trying to get the version of the ABI for the current deployment in the Block Explorer on in some tests.
We will add enpoints to get ABI of the contracts in the `nightfall-client` and `nightfall-optimist` the same we have now with `contract-address`.
The endpoint will be `contract-abi`.
Example:
```
curl http://localhost:8080/contract-abi/State 
```
Issue #990
> Add contract-abi endpoints to client/optimist

- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/ChallengesUtil.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-optimist/src/classes/block.mjs
- nightfall-optimist/src/routes/transaction.mjs
- nightfall-optimist/src/services/challenges.mjs
- nightfall-optimist/src/services/check-block.mjs
- nightfall-optimist/src/services/database.mjs
- nightfall-optimist/src/services/process-calldata.mjs
- nightfall-optimist/src/services/state-sync.mjs
- nightfall-optimist/src/services/transaction-checker.mjs
- test/adversary/transpile-adversary.mjs
This PR adds a series of optimizations for the current challenges. It does the following changes:
- leafCount is no longer the amount of commitments in the merkle tree before insertion. With this change, leafCount is now the amount of commitments **after** insertion.
- The siblingPath info is stored for the transactions merkle tree.
- The whole set of transactions contained in a block is no longer sent as part of the calldata in challengeDuplicateNullifier and challengeDuplicateCommitment. Instead, we verify that the transaction is real by verifying its sibling path.
- For the challengeProofVerification, there's no need of sending the whole transactions contained in a block. We just need to check that the historicBlock is real. A new function that only validates the block is created in …
> Optimizing challenges

- nightfall-deployer/src/contract-setup.mjs
Fix: #994 
Deployer is failing with an error at the end. Also `State` contract is not transferring ownership to multisig.
I have divided for readability the contracts in 2 groups.
- `contractsState` that will call `setStateContract` . (Proposers, Shield, Challenges)
- `contractsOwnables` that will call `transferOwnership` . (Proposers, Shield, Challenges, State)
Yes. #994
> fix: setup contracts script

- docker/admin.Dockerfile
- docker/client.Dockerfile
- docker/docker-compose.yml
- docker/optimist.Dockerfile
- nightfall-administrator/docker-entrypoint.sh
- nightfall-administrator/src/services/database.mjs
- nightfall-client/docker-entrypoint.sh
- nightfall-optimist/docker-entrypoint.sh
- package-lock.json
- package.json
- test/optimist-resync.test.mjs
Client, Optimist and Administrator do not use a MongoDB image anymore, but a Node one.
A new container only for MongoDB was created.
No
No
No
> Client, Optimist and Administrator now use a Node image

- common-files/utils/crypto/crypto-random.mjs
- doc/in-band-secret-distribution.md
- nightfall-client/src/services/kem-dem.mjs
- wallet/src/common-files/utils/crypto/crypto-random.js
- wallet/src/nightfall-browser/services/kem-dem.ts
This fixes some issues brought up as part the audit review
1. `randValueLT` used in KEM-DEM selects an element from the `BABYJUBJUB Sub Group Order` (Group_Order / cofactor), the random value is also checked to be non-zero
2. Error thrown in `packSecrets` have been removed or updated. 
3. Comments about `forward secrecy` removed.
> KEM-DEM Audit fixes 

- common-files/utils/logger.mjs
- common-files/utils/utils.mjs
Basically, when in local environments the logger will issue logs in a non-JSON format and, when in other envs, will use JSON format.
Nope
Nope
Nope
> Using non-JSON logging only for local envs

- nightfall-client/src/services/commitment-storage.mjs
When we store ERC721 tokens we set the value to `0` (since we care about `tokenId`). Filtering commitments above 0 value is preventing `/pending-deposit` and `/pending-spent` from returning info re ERC721.
n/a
n/a
n/a
> fix: updated filter conditions in client balances to return erc721 data

- setup-nightfall
This fixes the bug in master where, running locally, deployer cannot find the package`cls-hooked`.
No
This can be tested in the normal way with `npm t`
The bug is actually that the build of the `deployer` container is missing from `./setup-nightfall` and so the new package is not included in the container.
> fix: 'cannot find cls-hooked' bug in master

- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
Currently, a user could potentially send a deposit off-chain to a proposer and this deposit could be added to a valid block without having escrowed the funds first. To solve this problem, a new mapping called `isEscrowed(uint256 => bool)` is added. This mapping checks if the funds for a transaction hash has been deposited. It is only set to true when submitting a deposit transaction using `submitTransaction`. Then, when a proposer calls `proposeBlock` it will check that all transactions with transaction type 0 (deposits) has been escrowed by checking the mapping.
This PR also contains a major refactor of the assembly code contained in `proposeBlock` to make it more understandable and organized. 
It also adds two new const variables in Config.sol that are the number of slots used in the …
> proposeBlock prevents to add a deposit that has not previously escrowed its funds using submitTransaction

- config/default.js
- nightfall-deployer/src/circuit-setup.mjs
- zokrates-worker/src/app.mjs
- zokrates-worker/src/routes/checkCircuitHash.mjs
- zokrates-worker/src/routes/getCircuitHash.mjs
- zokrates-worker/src/services/checkCircuitHash.mjs
- zokrates-worker/src/services/getCircuitHash.mjs
The goal of this pr is to check if there have been any changes to the circuits and if so, go to force a trusted setup. 
To do this is kept within the `/output/circuithash.txt` (in the worker), the list of all circuits with their hash. 
So it checks if the hash of the current circuit differs, or is not in the file, and in case a trusted setup is forced
Resolves #989
> Force trusted setup if circuits have been modified

- .github/workflows/check-PRs.yml
- apps/proposer/config/default.js
- apps/proposer/src/proposer.mjs
- cli/lib/nf3.mjs
- config/default.js
- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/contracts/Proposers.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/database.mjs
- test/adversary.test.mjs
- test/circuits.test.mjs
- test/e2e/protocol/proposer.test.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
- test/gas.test.mjs
- test/optimist-resync.test.mjs
- test/ping-pong/ping-pong.test.mjs
- test/utils.mjs
Feat #726
Fixes #724
Implement proposer selection and staking based on the PR #506 that was developed in a feature branch following the proposal #283.
- Add operations in the contracts for staking ETH. In the future decide if it's ETH or MATIC.
- Add/Update endpoints for this proposers staking in optimist.
- Add/Update operations to SDK for this proposers staking.
- This staking will be the base of the staking power when running spans of the weighted round robin algorithm for proposers selection in next task
- Implement weighted round robin algorithm based on the proposer staking for proposer selection
- registerProposer now pass the amount to stake instead of bond. 
- updateProposer could update the URL and increment the stake .
- No REGISTRATION_BOND now but a MINIMUM_STAKE (100 wei for …
> Implement PoS for proposers

- docker/docker-compose.adversary.yml
- docker/docker-compose.yml
- nightfall-optimist/src/event-handlers/challenge-commit.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- test/adversary.test.mjs
This PR make adversary.test.mjs to make websocket connection to optimist instead of adversary container which run a challenger
https://github.com/EYBlockchain/nightfall_3/issues/885
evidence: temporary successful github workflow run created on this branch https://github.com/EYBlockchain/nightfall_3/actions/runs/3150503026/jobs/5123363365
> optimist as a challenger instead of adversary for adversary.test.mjs

- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
Move `saveTransaction` within the try/catch block without changing functionality
#1048 
Restart optimist with nonempty database
> save transaction

- common-files/utils/httputils.mjs
A quick fix to prevent an HTTP header of having an invalid value
No
`npm run test-e2e-protocol && npm run test-e2e-tokens` 
No
> Fix HTTP header with an invalid value for correlationId

- common-files/package-lock.json
- doc/kyc.md
- nightfall-administrator/src/index.mjs
- nightfall-administrator/src/services/contract-calls.mjs
- nightfall-administrator/src/services/contract-transactions.mjs
- nightfall-administrator/src/services/helpers.mjs
- nightfall-administrator/src/ui/get-info.mjs
- nightfall-administrator/src/ui/menu.mjs
This provides the `Administrator` container's `./admin` app with extra menu items that enable admin control of the whitelisting process, i.e.:
- Adding and removing whitelist managers
- Enabling/disabling whitelisting
- Checking if an address is a whitelist manager
Before this PR, these items could only be set at the point of contract deployment.
Note that these functions are the ones that must only be called by the contract multisig.  Whitelist managers do not have this level of access.  They access their whitelisting API via the client container (this is already merged).
fixes #742 
Currently it is not possible to test the administrator container automatically.  This will be fixed by the upcoming issue #1037 and so is not addressed in this PR.
To test manually, read the instructions in …
> KYC admin functions

- common-files/utils/contract.mjs
- test/ping-pong/ping-pong.test.mjs
This PR fixes bug in ping-pong-test, only visible in AWS where there is a proposer running. This test starts a second proposer with the same optimist, and the first one loses connection to optimist and its not able to receive blocks.
No
run ping pong test
> do not register second proposer in ping pong test in AWS

- cli/lib/nf3.mjs
- nightfall-client/src/services/deposit.mjs
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- wallet/src/nightfall-browser/services/deposit.js
- wallet/src/nightfall-browser/utils/compute-witness.ts
This PR should be merged after #1033.
Transaction structure contains a fee field which right now can be either matic (L2 token) or ether value, which makes it confusing for users. This PR fixes this behaviour by only storing the fees paid in L2. If the fees are paid in L1 (aka when deposit) the fee in the transaction is set to 0 and fee is stored in a mapping in the Smart Contract.
> Fees upgrade

- apps/proposer/src/routes/proposer.mjs
- cli/lib/nf3.mjs
- nightfall-deployer/contracts/Proposers.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-optimist/src/routes/proposer.mjs
- test/adversary.test.mjs
- test/circuits.test.mjs
- test/e2e/protocol/proposer.test.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
- test/gas.test.mjs
- test/kyc.test.mjs
- test/multisig/administrator.test.mjs
- test/utils.mjs
Fixes: #936 
- Add/update fee for the proposer
- Get fee for the proposer. Endpoint defined in the proposer app `/proposer/fee`.
Yes. #936.
npm run test-e2e-protocol
No
> Proposer fee endpoint and update

- .github/workflows/check-PRs.yml
This PR updates `setup-node` pipeline step to `v3`. This should speed things up a little and remove the warning messages about outdated versions of node from the pipeline results.
Closes #1082 
Have a good day 👋
> #1082: Update setup-node step to v3

- .github/workflows/check-PRs.yml
Updates the dependency review action to use the latest version. The current version is 2.4.1.
No
It runs in the GA pipeline
No
> Dependency review version update

- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- test/unit/SmartContracts/shield.unit.test.mjs
- test/unit/utils/shieldStorage.mjs
- test/unit/utils/stateStorage.mjs
This PR adds a few fixes to PoS implementation. 
1. When calling `proposeBlock`, if the proposer's stake is less than the blockStake the transaction submitted will revert. To avoid this and provide more clarity, a require is added so that if the proposer doesn't have enough funds, a message will be thrown.
2. When calling `requestBlockPayment`, the proposer is getting back their locked funds for the challenge. However, during the challenge period the blockStake might have changed (or in a future a functionality will be enabled to do so). Therefore, we need to make sure that the proposer receives what he staked (not more, not less). To do so, we store for each block the amount staked. 
3. If a block is succesfully challenged, the challenger will get the stake for that block and all the …
> PoS minor fixes

- .github/workflows/on-pull-request-master.yml
- docker/admin.Dockerfile
- docker/client.Dockerfile
- docker/deployer.Dockerfile
- docker/optimist.Dockerfile
- docker/proposer.Dockerfile
- docker/worker.Dockerfile
Adds missing `npm link` instructions to Github Actions pipeline.
No
No, but GA pipeline should work as expected
No
> Adding missing npm linking

- common-files/utils/mongo.mjs
- test/gas.test.mjs
- test/optimist-resync.test.mjs
- gas test was occasionally failing because of a timeout in mongodb. This error seemed to happen after we created a separate mongoDb instance.  I increased this timeout to 1 second.
- optimist-sync test seem to occasionally fail for the same reason.
- Remove unnecessary code from gas test to make it faster. Before, we were testing single and double transfers. But there is no such distinction anymore. To be able to test both transfers, we needed to have two rounds of deposits. I just left one. 
#1128 and #1125
GHA will test these changes, specifically `gas-test` and `optimist-sync` test
> Fixed gas and resync tests

- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/Structures.sol
- test/unit/SmartContracts/shield.unit.test.mjs
- test/unit/utils/shieldStorage.mjs
This PR adds a minor optimization to the Shield Contract by creating a structure that unifies withdrawn and isEscrowed mappings into a single one. This way we save 20.000 gas in storage costs.
It also adds a require to the payout function so if the ercAddress is higher than 2^160 it will fail.
No
The corresponding tests has been upgraded. Can be tested running `npm run unit-test-shield`
N/A
> Shield Contract minor optimization

- docker/docker-compose.yml
env variable `ALWAYS_DO_TRUSTED_SETUP` forces to do a trusted setup. This variable needs to be passed to the deployer container.
No
> Add ALWAYS_DO_TRUSTED_SETUP to deployer container

- nightfall-deployer/contracts/State.sol
Currently, there is a bug in the proposeBlock function when checking that a deposit was escrowed. The function wasn't properly called, but the memory location it was checking also passed the checked and hence it wasn't detected.
> fix: assembly code bug

- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- test/optimist-resync.test.mjs
Added additional test case to optimist-sync test where we restart optimist without dropping the Db. This is testing what issue https://github.com/EYBlockchain/nightfall_3/issues/1077 reports.
#1077 and #1051
GHA test (resync tests)
> Test optimist resync with non empty dB

- docker/client.Dockerfile
- docker/docker-compose.dev.yml
- docker/optimist.Dockerfile
- hosted-utils-api-server/Dockerfile
- hosted-utils-api-server/package.json
- nightfall-client/package.json
- nightfall-optimist/package.json
This PR enables debugging on dev env. This is going to help a lot with local debugging. Chromium debugger, VSCode and probably plenty other tools can now hook into ports to enable local debugging. Ports to debug individual services listed below:
- `9229` - nightfall-optimist
- `9239` - nightfall-client
- `9249` - hosted-utils-api-server
Because we already have some VSCode specific configuration in our repo, I allowed myself to add debugger configurations for individual services (`./vscode/launch.json`).
> feat: Open debugger ports on client, optimist and hosted-utils-api-server

- .github/workflows/on-pull-request-master.yml
- common-files/classes/transaction.mjs
- config/default.js
- nightfall-client/src/services/process-calldata.mjs
- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/contracts/Structures.sol
- nightfall-deployer/contracts/Utils.sol
- nightfall-optimist/src/services/process-calldata.mjs
- test/unit/SmartContracts/shield.unit.test.mjs
- test/unit/SmartContracts/state.unit.test.mjs
- test/unit/utils/utils.mjs
- wallet/src/common-files/classes/transaction.js
- wallet/src/nightfall-browser/services/process-calldata.js
This PR optimizes the transaction struct by storing value (uint112), fee (uint96), circuitHash(uint40) and tokenType(uint8) in a single uint256 slot. This should reduce the gas used per transaction in proposeBlock by around 1500 gas. This also reduces the cost of the calldata by around a 10 - 15 % whenever the transaction struct is passed.
Yes, it closes #1174 
It is enough if all the tests go through
> Transaction Structure optimization

- apps/proposer/config/default.js
- apps/proposer/src/proposer.mjs
- cli/lib/constants.mjs
- cli/lib/nf3.mjs
- config/default.js
- doc/lib/nf3.mjs.html
- test/adversary.test.mjs
- test/circuits.test.mjs
- test/e2e/protocol/proposer.test.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
- test/gas.test.mjs
- test/kyc.test.mjs
- test/multisig/administrator.test.mjs
- test/optimist-resync.test.mjs
- test/ping-pong/ping-pong.test.mjs
- test/utils.mjs
Fix #1172.
Change all constants for MINIMUM_STAKE and BLOCK_STAKE used in tests for the corresponding variable of the blockchain defined in `Config.sol` contract.
Yes. #1172.
Any e2e test that use and register proposers.
No
> Get minimum and block stake from the blockchain

- common-files/package.json
Changes `common-files` current version to `0.0.7`. The trigger solution implemented recently is failing because of the `branch protection rules` in place.
No
No
We need to figure out how to do this automatically. Github allows us to create a new `role` with a more relaxed permission that might be used in this case however, this is not the best way.
> Applying manual change to common-files version 0.0.7

- common-files/package.json
Some changes in the common-files weren't still published when the [PR](https://github.com/EYBlockchain/nightfall_3/pull/1183) merged which generated the version `0.0.8`.
No
No
No
> Updates common-files to 0.0.8

- docker/docker-compose.yml
- docker/hosted-utils-api-server.Dockerfile
Move `hosted-utils-api-server` Docker file to `docker` folder, where all Docker config files are located.
> Move utils Dockerfile to appropriate location

- wallet/src/components/Modals/txInfoModal.tsx
- wallet/src/components/Transactions/index.jsx
Simple fix for wallet withdraw type. Type was 3 and should be 2.
Also, remove 7 day `CHALLENGE_PERIOD` check, and call contract to verify if `CHALLENGE_PERIOD` has passed. This will allow to set different `CHALLENGE_PERIOD`
No
> Wallet: set withdraw type to 2

- cli/lib/nf3.mjs
- common-files/utils/httputils.mjs
- docker/docker-compose.apps.yml
- nightfall-client/src/routes/commitment.mjs
- nightfall-client/src/services/commitment-storage.mjs
- test/e2e/tokens/erc721.test.mjs
Several adjustments to make nightfall work with the SDK with future `tokenization` branch:
- filter unspent commitments. Burning transaction requires to burn at most a commitment, so we need to check number of existing unspent commitments. Modified nf3 `getLayer2Commitments` to accept a list of compressedZkpKeys and a list of ercAddresses to filter commitments
- add `salt` to obfuscation
- add `PROPOSER_PORT` and `PROPOSER_HOST` to proposer container env variables to allow to communicate client and proposer containers. Without this, client attempts to connect to `localhost:8092`, and this route is not enabled between containers. With the env variables, the proposer can register at `nightfall_3-proposer-1:8092` and that works.
No
erc721.test includes verification of commitments
No
> filter commitments

- nightfall-deployer/contracts/Config.sol
- nightfall-deployer/contracts/State.sol
- test/multisig/administrator.test.mjs
- test/multisig/nightfall-multisig.mjs
- test/ping-pong/index.mjs
- test/unit/SmartContracts/state.unit.test.mjs
- test/unit/utils/shieldStorage.mjs
- test/unit/utils/stateStorage.mjs
Fix #1189 . Calculate the slot value dynamically for calculating the staking power of each proposer in next span of the PoS.
Yes. #1189 
npm run test-e2e-protocol
No
> Calculate slot value in PoS dynamically

- config/default.js
- doc/sanctions_list.md
- docker/docker-compose.dev.yml
- nightfall-deployer/contracts/SanctionsListInterface.sol
- nightfall-deployer/contracts/Shield.sol
- nightfall-deployer/contracts/mocks/SanctionsListMock.sol
- nightfall-deployer/migrations/2_deploy_upgradeable.js
- test/e2e/tokens/erc20.test.mjs
- test/unit/SmartContracts/challenges.unit.test.mjs
- test/unit/SmartContracts/proposers.unit.test.mjs
- test/unit/SmartContracts/shield.unit.test.mjs
- test/unit/SmartContracts/state.unit.test.mjs
This PR adds checking against the Chainalysis sanctions-screening oracle smart contract before allowing a deposit or final withdrawal transaction.  More details are give in [sanctions_list.md](https://github.com/EYBlockchain/nightfall_3/blob/westlad/sanctions/doc/sanctions_list.md)
fixes #1209
All tests have been upgraded to test this functionality via a stub contract, so normal test scripts can be run. In particular, the Shield contract unit and the erc20 token integration tests now specifically test this functionality.
None
> Add check against sanctions list

- nightfall-deployer/contracts/Challenges.sol
- test/unit/utils/utils.mjs
Expands the historicRootBlockNumber challenge to also handle the case where the number of historic roots specified is greater than the number of nullifiers.
This doesn't really represent an attack vector, it's just for completeness
Run the adversary test or the contract unit tests.
> Historic root challenge

- .github/workflows/on-pull-request-master.yml
- nightfall-deployer/contracts/Shield.sol
- test/unit/SmartContracts/shield.unit.test.mjs
This allows the maximum value of tokens that can be moved in/out of layer 1 to be turned off, should the deployer require that. This can be achieved by setting the deposit and/or withdraw restrictions to zero.  `Shield.sol` checks for a zero value and, if found, bypasses the restriction value check.
fixes #1238 
The Shield unit test has been updated to test for this change
> Setting a token restriction to zero turns it off

- cli/lib/nf3.mjs
- cli/package.json
- config/default.js
- nightfall-optimist/src/utils/auth.mjs
- test/circuits.test.mjs
- test/e2e/protocol/proposer.test.mjs
- test/multisig/administrator.test.mjs
This removes the existing hash function from the auth logic . It serves the purpose of simplifying and using an .env variable as the auth token for the proposer routes.
no
npm run test-e2e-protocol            
It is suggested for the deployer to use UUID(https://www.uuidgenerator.net/) as the authentication token. However, the code doesn't stop the deployer to use whatever string they want.
Updated administrator and circuits tests.
> chore: remove hashing function

- nightfall-deployer/circuits/burn.circom
- nightfall-deployer/circuits/common/utils/array_uint32_to_bits.circom
- nightfall-deployer/circuits/common/utils/calculate_keys.circom
- nightfall-deployer/circuits/common/utils/calculate_root.circom
- nightfall-deployer/circuits/common/utils/kem_dem.circom
- nightfall-deployer/circuits/common/verifiers/commitments/verify_commitments.circom
- nightfall-deployer/circuits/common/verifiers/commitments/verify_commitments_generic.circom
- nightfall-deployer/circuits/common/verifiers/commitments/verify_commitments_optional.circom
- nightfall-deployer/circuits/common/verifiers/nullifiers/verify_nullifiers.circom
- nightfall-deployer/circuits/common/verifiers/nullifiers/verify_nullifiers_generic.circom
- nightfall-deployer/circuits/common/verifiers/nullifiers/verify_nullifiers_optional.circom
- nightfall-deployer/circuits/common/verifiers/verify_duplicates.circom
- nightfall-deployer/circuits/common/verifiers/verify_encryption.circom
- nightfall-deployer/circuits/deposit.circom
- nightfall-deployer/circuits/tokenise.circom
- nightfall-deployer/circuits/transfer.circom
- nightfall-deployer/circuits/withdraw.circom
- test/unit/circuits/common/utils/calculate_keys.circom.test.mjs
- test/unit/circuits/common/utils/calculate_root.circom.test.mjs
- test/unit/circuits/common/utils/kem_dem.circom.test.mjs
- test/unit/circuits/common/verifiers/commitments/verify_commitments.circom.test.mjs
- test/unit/circuits/common/verifiers/commitments/verify_commitments_generic.circom.test.mjs
- test/unit/circuits/common/verifiers/commitments/verify_commitments_optional.circom.test.mjs
- test/unit/circuits/common/verifiers/nullifiers/verify_nullifiers.circom.test.mjs
- test/unit/circuits/common/verifiers/nullifiers/verify_nullifiers_generic.circom.test.mjs
- test/unit/circuits/common/verifiers/nullifiers/verify_nullifiers_optional.circom.test.mjs
- test/unit/circuits/common/verifiers/verify_duplicates.circom.test.mjs
- test/unit/circuits/common/verifiers/verify_encryption.circom.test.mjs
Updates circom circuits from version 2.1.0 to 2.1.2, which fixes a bug in the witness generator (although it doesn't impact our project because we are using wasm files to generate the witness)
> fix: bumping circom version to 2.1.2

- hardhat.config.ts
- nightfall-deployer/contracts/State.sol
- test/unit/SmartContracts/state.unit.test.mjs
Instead of leaving it to the `changeCurrentProposer` each time to calculate from scratch the `nextProposer`, the next n are calculated all at once, so that we know in advance what the next ones will be, and stimulate to execute the function for changing proposer
Gas comparison is made on two functions modified in this pr (`setNumProposers`, `changeCurrentProposer`).
| | Previous Version | New Version |
| :---         |     :---:      |          ---: |
| np != 2   | 33208  | 33246   |
| np == 2    | 36008       | 346445      |
In this case, the new version is more expensive in case `numproposers` = 2 because it is calculated the list of next proposers.
The first time the setNumProposers is executed with np == 2 and the changeCurrentProposer is called the cost in gas is:
| min | max | avg | …
> ChangeCurrentProposer - calculation of the next proposers

- .github/workflows/on-pull-request-master.yml
- bin/setup-nightfall
- common-files/utils/web3.mjs
- config/default.js
- docker/docker-compose.apps.yml
- docker/docker-compose.client.yml
- docker/docker-compose.yml
- hosted-utils-api-server/entrypoint.sh
- nightfall-client/src/app.mjs
- nightfall-client/src/index.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/start-client
- nightfall-deployer/src/circuit-setup.mjs
- nightfall-optimist/src/routes/proposer.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- wallet/package.json
- wallet/src/components/Transactions/index.jsx
- wallet/src/nightfall-browser/services/fetch-circuit.js
- wallet/src/web-worker/index.js
- worker/src/index.mjs
- `setContractState` and `transferOwnership` usually fail in goerli deployment. The reason is because there is no gas estimation being done
- Allow passing the name for both optimist and commitments db. The reason is to allow different optimists and clients to use the same AWS cluster and just have different names.
- `PROPOSER_MAX_BLOCK_PERIOD_MILIS` configures the maximum time that a proposer can wait to generate a block if there are pending transactions.
- AWS document db requires different format for db projections
- circuit registration usually failed in Goerli deployment because there was no gas estimation being done
- In some tests i found that the proposer wasn't set even though addresses matched. This case is fixed now
- Correct `proposer` and `hosted-utils-api-server` containers …
> several fixes for aws deployment

- nightfall-client/src/event-handlers/subscribe.mjs
- nightfall-client/src/services/state-sync.mjs
- nightfall-optimist/src/event-handlers/index.mjs
- nightfall-optimist/src/services/state-sync.mjs
- nightfall-optimist/src/services/transaction-checker.mjs
- test/adversary.test.mjs
- test/utils.mjs
Since `emit Rollback` was moved into Challenges and the client was only listening for events for the State contract, rollback events weren't caught by the client, creating discrepancies between optimist and client database. 
In order to avoid similar issues in a future, the client is now subscribed to all the contracts. This doesn't have any impact to the client behaviour since all those events that are not handled are simply ignored.
State sync event handling has been fixed for both: client and optimist.
An additional log has been added to transaction checker to help us detect root discrepancies easier.
N/A
N/A
N/A
> Client was not doing rollbacks

- cli/lib/nf3.mjs
- config/default.js
- doc/pos.md
- nightfall-deployer/contracts/Config.sol
- test/e2e/protocol/proposer.test.mjs
- test/ping-pong/index.mjs
Initial configuration for the PoS according to the conclusion in https://hackmd.io/m_85iGlMTzGkc4hZSElTKQ?both
- MINIMUM_STAKE: 20K MATIC 
- BLOCK_STAKE: 200 MATIC
- ROTATE_PROPOSER_BLOCKS: 32 blocks
- VALUE_PER_SLOT: Maximum stake of a proposer / 10
- SPRINTS_IN_SPAN: 10
- PROPOSER_SET_COUNT: 10
Yes. #1248.
npm run test-e2e-protocol
No
> Initial values for the PoS

- apps/utils/oid-encoder.mjs
- doc/adding_certificates.md
This adds to the docs a write up on how to add x509 certificates and trust roots to Nightfall.  Please note that it assumes PR #1259 has been merged and some of the features it refers to are only included in that PR
Contributes to issue #1234 but does not complete it.
This is mainly documentation, so no tests. The small utility included does not have associated tests. However you can check that `node apps/utils/oid-encoder.mjs 1.2.3.4` outputs
`0x2a03040000000000000000000000000000000000000000000000000000000000`
> documentation about adding certificates to nightfall.

- nightfall-client/src/utils/getCommitmentInfo.mjs
When performing any action (deposit, transfer, burn...) the function `getCommitmentsInfo` is called. This function has two parameters called `maxNullifiers`, which is the max number of nullifiers that the circuits allow, and `maxNonFeeNullifiers`, which is the max number of nullifiers that aren't used for the fee. If not specified, this second parameter is `undefined` by definition.
Also, if the token transferred ercAddress is the same than the fee ercAddress, the values are added together and fee is set to zero. This is done because when a commitment is selected is moved to `pendingNullified` and so if this wasn't done an error would be thrown. However, this should only be done if `maxNonFeeNullifiers` is not set to zero and hence this is fixed in this PR.
The second fix is related to …
> Minor maxNonFeeNullifiers logic fixes

- apps/proposer/src/proposer.mjs
fixed the typo in the condition `spanProposersList[currentSprint] === nf3.ethereumAddress` with `spanProposersListAtPosition === nf3.ethereumAddress`
that did not allow the changecurrentproposer to be called from the correct address
No
./bin/start-multiproposer-test-env -g
docker logs -f proposer_1
docker logs -f proposer_2
> fix automatic changeCurrentProposer

- test/e2e/tokens/erc20.test.mjs
- test/ping-pong/index.mjs
- test/utils.mjs
Adds a `waitForTransactionsMempool` utils function that waits for having enough transactions in the mempool before creating a block. This should considerably remove the time that takes the erc20 test to run
No
npm run test-erc20-tokens
> Erc20 testing restriction

- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/rollback.mjs
- nightfall-optimist/src/services/block-assembler.mjs
- nightfall-optimist/src/services/database.mjs
- test/adversary.test.mjs
Once a block was assembled by a proposer, transactions were erased from the mempool by calling `removeTransactionsFromMempool` so that the same transaction isn't proposed twice. In addition to that, two extra functions were called: `removeNullifiersFromMempool` and `removeCommitmentsFromMempool`. Since a good optimist can not have duplicate nullifiers nor commitments in their DB (when transaction received, the fee is checked and only the one with highest fee is kept) those functions aren't needed anymore because they will have no impact.
On the other hand, this three functions are called when a block is proposed. In this case, it might be the case in which an optimist has a different transaction in his mempool with the same nullifier of a transaction that has been assembled into a block. …
> Optimist fixes

- common-files/classes/proof.mjs
- common-files/classes/transaction.mjs
- common-files/utils/curve-maths/curves.mjs
- nightfall-client/src/services/burn.mjs
- nightfall-client/src/services/deposit.mjs
- nightfall-client/src/services/process-calldata.mjs
- nightfall-client/src/services/tokenise.mjs
- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
- nightfall-deployer/contracts/Challenges.sol
- nightfall-deployer/contracts/ChallengesUtil.sol
- nightfall-deployer/contracts/Utils.sol
- nightfall-optimist/src/services/challenges.mjs
- nightfall-optimist/src/services/process-calldata.mjs
- nightfall-optimist/src/services/transaction-checker.mjs
- package-lock.json
- package.json
- test/adversary.test.mjs
- test/unit/SmartContracts/challenges.unit.test.mjs
- test/unit/SmartContracts/compression.unit.test.mjs
- test/unit/SmartContracts/proposers.unit.test.mjs
- test/unit/SmartContracts/shield.unit.test.mjs
- test/unit/SmartContracts/state.unit.test.mjs
- wallet/src/common-files/classes/transaction.js
- wallet/src/nightfall-browser/services/deposit.js
- wallet/src/nightfall-browser/services/transfer.js
- wallet/src/nightfall-browser/services/withdraw.js
Instead of passing in uncompressed proofs and checking its compression against the transaction, we now directly decompress the proof inside the transaction.
This prevents a possible attack due to the non-bijective mapping from the compression function, which would allow any transaction to be challengeable.
`npm run unit-test-compression`
> Decompress proof on-chain

- nightfall-deployer/src/circuit-setup.mjs
- worker/src/routes/vk.mjs
- worker/src/utils/filing.mjs
In some cases the deployer gets stucked checking the circuits and downloading them from the worker.
It has been detected that the function that sometimes is blocking the `deployer` is `getVerificationKeyByCircuitPath` from the `worker` in `filling.mjs` in the line when the verification key is exported with snarkjs (`snarkjs.zKey.exportVerificationKey`).
```
export const getVerificationKeyByCircuitPath = async circuitPath => {
const vkPath = `${outputPath}/${circuitPath}/${path.basename(circuitPath)}.zkey`;
if (fs.existsSync(vkPath)) {
const vk = await snarkjs.zKey.exportVerificationKey(vkPath);
return vk;
}
logger.warn({ msg: 'Unable to locate file', vkPath });
return null;
};
```
If we don't do all the calls in parallel to get the verification keys of the circuits with `promise.all` and …
> fix deployer get circuits in some cases

- apps/proposer/src/proposer.mjs
- cli/lib/nf3.mjs
- test/unit/SmartContracts/state.unit.test.mjs
added some logs to see the list of proposers at sprint 0 and the next proposer at each sprint
./bin/start-multiproposer-test-env -g
docker logs -f proposer_1
docker logs -f proposer_2
> changeCurrentProposer log improvement

- cli/lib/nf3.mjs
- nightfall-client/src/routes/burn.mjs
- nightfall-client/src/routes/deposit.mjs
- nightfall-client/src/routes/tokenise.mjs
- nightfall-client/src/routes/transfer.mjs
- nightfall-client/src/routes/withdraw.mjs
- nightfall-client/src/services/burn.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/src/services/database.mjs
- nightfall-client/src/services/deposit.mjs
- nightfall-client/src/services/tokenise.mjs
- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/services/withdraw.mjs
- nightfall-client/src/utils/getCommitmentInfo.mjs
- test/adversary/adversary-code/commitment-storage.mjs
- test/adversary/transpile-client-adversary.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
- test/e2e/tokens/l2tokenisation.test.mjs
- test/utils.mjs
- wallet/src/nightfall-browser/services/commitment-storage.js
- wallet/src/nightfall-browser/services/database.js
- wallet/src/nightfall-browser/services/deposit.js
- wallet/src/nightfall-browser/services/transfer.js
- wallet/src/nightfall-browser/services/withdraw.js
- wallet/src/nightfall-browser/utils/getCommitmentInfo.ts
This PR modifies the logic allowing the user to specify the commitment hashes they wanna use. With the current changes, it will work as follows:
- Users will be able to provide commitment hashes for either the fee or the value, using `providedCommitments` and `providedCommitmentsFee` respectively. 
- All commitments provided will be used. If more commitments than the number of max number of nullifiers is sent, an error will be thrown. If any of the commitments doesn't belong to the value address or the fee address, an error will be thrown. 
- If the user provide commitments for the value, they should cover the whole amount. Otherwise an error will be thrown. Same applies for the fee.
Routes have been updated to throw any error that is thrown. 
Transpilation for the adversary has been …
> User can provide either fee or value commitments

- nightfall-deployer/contracts/X509.sol
Currently, when we validate either an intermediate CA certificate or an end-user certificate, we add their public keys to the list of keys that the smart contract trusts.  We should not be doing this for an end-user certificate because it would enable the holder of an end-user certificate to act as an intermediate CA and create their own end user certificates.
This fix stops adding end-user public keys to the trusted keys list.
No, it's a bug-fix
You can run `npm run unit-test-x509`
It's an important fix.
> trusted key bug

- nightfall-deployer/contracts/Proposers.sol
solves the problem that occurred when two proposers were registered, but the `spanProposersList` that was built contained only 1 proposer instead of 2. this was due to the fact that the `numproposer` was incremented before the `currentProposer` was set
`./bin/start-multiproposer-test-env -g`
then: 
`docker logs -f proposer_1`
from the logs it will be possible to see the printed `spanProposersList` containing both the proposers
> fix: registerProposer

- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/event-handlers/rollback.mjs
- nightfall-client/src/services/commitment-storage.mjs
- nightfall-client/src/services/commitment-sync.mjs
- nightfall-client/src/services/database.mjs
- nightfall-optimist/src/event-handlers/rollback.mjs
- nightfall-optimist/src/services/check-block.mjs
- nightfall-optimist/src/services/transaction-checker.mjs
- test/adversary.test.mjs
- test/adversary/adversary-code/incorrectTransactions.mjs
- test/e2e/tokens/erc20.test.mjs
- test/optimist-resync.test.mjs
- test/utils.mjs
- wallet/src/nightfall-browser/event-handlers/block-proposed.js
- wallet/src/nightfall-browser/event-handlers/rollback.js
- wallet/src/nightfall-browser/event-handlers/subscribe.js
- wallet/src/nightfall-browser/services/commitment-storage.js
- wallet/src/nightfall-browser/services/database.js
This PR fixes deep rollbacks in both, optimist and client. We can assume that a deep rollbacks are any rollbacks that doesn't take place just after the bad block was introduced but a few blocks after.
When a deep rollback happens, we will consider the following:
- Bad transactions are removed (for obvious reasons)
- If all nullifiers are commitments that were added prior to the rollback, the transaction is considered valid. Otherwise, the transaction is removed from the mempool.
In order to fix deep rollbacks in the optimist, the check for historic root block number has been modified. So, instead of relying on the database, it will rely on the blockchain to get the latest valid block number.
The rollback in the client has been completely rewritten to work with this new logic. Some other …
> Fixing deep rollbacks

- docker/docker-compose.apps.yml
Client couldn't reach proposer eg when sending offchain transactions. Have added a couple of defaults to the docker compose apps file, to resolve the proposer host and port successfully.
> fix: add proposer host, port defaults to proposer app

- cli/lib/nf3.mjs
- common-files/utils/event-queue.mjs
- wallet/src/common-files/utils/event-queue.js
This fixes an issue that can happen when errors aren't properly caught by the queues. The queues being used are emitters and when there isn't a listener for an 'error' event for that queue and an error happens, the application crashes. 
Follows the log of a test performed locally:
```
optimist_1       | [2023-01-06 14:25:49.066] DEBUG: Block Assembler - about to make a new block
optimist_1       |     correlationId: "579dd1c6-1ad5-448e-89f3-90c1173cc75c"
optimist_1       | file:///app/node_modules/@polygon-nightfall/common-files/utils/block-utils.mjs:27
optimist_1       |   const proposerPacked = generalise(proposer).hex(20).slice(2);
optimist_1       |                                              ^
optimist_1       | 
optimist_1       | TypeError: Cannot read properties of undefined …
```
> fix: Adding listener for queues on errors

- common-files/utils/mongo.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- nightfall-optimist/src/services/database.mjs
Reduces number of DB calls. Instead of blocking execution context twice for `deleteDuplicateCommitmentsFromMemPool` and `deleteDuplicateNullifiersFromMemPool` it performs the same operation using just one call to `deleteDuplicateCommitmentsAndNullifiersFromMemPool` and blocks the execution just once.
> refactor: optimize db calls to memepol cleanup

- wallet/src/hooks/User/index.jsx
- wallet/src/nightfall-browser/services/database.js
It handles a scenario where contracts were redeployed. Instead of of only checking for block number accuracy, it also makes sure the block hashes match.
Maybe.
Re-snc wallet on the env where contracts where redeployed.
It assumes that the enhancement to sync block Lambda are merged.
> Fix: Handle re-deployed contracts on wallet

- wallet/src/utils/CommitmentsBackup/commitmentsVerification.js
When importing commitments with the wallet, we should convert preimage.zkpKeys to compressed format before comparing with expected keys.
No
Export and Import commitments with wallet
No
> Wallet import commitments

- .github/workflows/on-pull-request-master.yml
- cli/lib/constants.mjs
- cli/lib/jobScheduler.mjs
- cli/lib/nf3.mjs
- cli/package-lock.json
- cli/package.json
- nightfall-deployer/contracts/State.sol
- nightfall-deployer/migrations/2_deploy_upgradeable.js
- nightfall-deployer/migrations/3_test_tokens_migration.js
- nightfall-deployer/migrations/4_upgrade_upgradeable.js
- nightfall-optimist/src/routes/proposer.mjs
- package.json
- test/fee-and-reward-periodic-payment.test.mjs
This PR implement a feature to `cli` SDK for proposer and challenger to start a cron job which withdraw their pending withdraw from state contract.
as part of the implementation it fixes few existing bugs:-
1.  fix state contract addPendingWithdrawal function - not to override existing added pendingWithdraw for an address
2. update `nightfall_deployer` migration files to do `state.setFeeL2TokenAddress` function
3. fix optimist router.get('/pending-payments') api to work with address not passed in lower case. As in our optimist DB we save EOA address in lowercase unlike  in ethereum where address in case sensitive
4. fix optimist router.get('/withdraw') api:- to  router.post('/withdraw') also correct logic to call withdraw function from state contract, before api had logic to call …
> periodic payment cron job for proposer and challenger

- cli/lib/nf3.mjs
Fixes an issue caused when trying to 'ping' by directly accessing the underlying ws while it is not in 'OPEN' state which
might lead to an error thrown (causing 'optimist-sync-test' to fail [spordically](https://github.com/EYBlockchain/nightfall_3/actions/runs/3948865503/jobs/6759374472) or crash 'proposer'/'challenger').
Not sure
run 'optimist-sync-test' locally or in ci:
```bash
NF_SERVICES_TO_START=blockchain,client,deployer,mongodb,optimist,rabbitmq,worker ./bin/setup-nightfall
NF_SERVICES_TO_START=blockchain,client,deployer,mongodb,optimist,rabbitmq,worker CONFIRMATIONS=1 ./bin/start-nightfall -g -d
npm run test-optimist-sync
```
- Consider reviewing [managment](https://dev.to/ndrbrt/wait-for-the-websocket-connection-to-be-open-before-sending-a-message-1h12) of websocket state in …
> avoid trying to 'ping' when ws state is not 'OPEN'

- .gitattributes
Makes sure on clone/checkout shell scripts are kept with linux file new line whitespaces otherwise if files are copied-over or bounded and executed from within a docker container if it uses windows CRLF shell will report that file does not exists or parsing error.
See: https://stackoverflow.com/questions/65320180/issue-with-line-endings-when-developing-on-a-windows-but-running-on-a-unix-docke
Nope
Clone and checkout 'master' branch on a windows machine and open shell scripts in notepad++ while viewing all symbols to make sure newlines LF (and maybe start some docker services with `-d` flag as a sanity check).
Nope
> add '.gitattributes' to prevent issues when using docker on windows

- .dockerignore
Currently all container images are built with a build context of the entire repo. 
The `.dockerignore` file helps avoiding sending over large or sensitive files to the docker daemon and copying these into images. It follows the same syntax as '.gitignore' and can work recursively (with wildcards such as '**/node_modules/').
**However, Docker/Podman CLI will [only look](https://medium.com/@LihauTan/took-me-hours-to-realise-why-docker-build-ignores-my-dockerignore-and-this-is-what-ive-learned-2f87c770ea9c) for .dockerignore file in the root directory of the context!** so all those '.dockerignore' files in sub-directories are ignored and the root file (the only one that counts) is far from being conclusive.
**This can be especially detrimental when working against a remote machine or a local …
> enrich root '.dockerignore'

- common-files/constants/constants.json
- config/default.js
- docker/docker-compose.deployment.yml
- docker/docker-compose.yml
- nightfall-client/src/routes/transfer.mjs
- nightfall-client/src/services/commitment-sync.mjs
- nightfall-client/src/services/kem-dem.mjs
- nightfall-client/src/services/transfer-regulator.mjs
- nightfall-client/src/services/transfer.mjs
- nightfall-client/src/utils/computeCircuitInputs.mjs
- nightfall-client/src/utils/regulator.mjs
- nightfall-deployer/circuits/common/utils/kem_dem.circom
- nightfall-deployer/circuits/common/verifiers/verify_encryption_regulator.circom
- nightfall-deployer/circuits/transfer_regulator.circom
- package.json
- test/kem-dem-regulator.test.mjs
- test/unit/circuits/transfer-regulator.circom.test.mjs
Update in the client to enable regulator for the transfers.
#1372 
Start nightfall with `REGULATOR_URL=http://localhost:8080 NF_SERVICES_TO_START=blockchain,client,worker,optimist,deployer ./bin/start-nightfall -g -d` to indicate a regulator url for the client to create transfers enabled for the regulator.
- npx hardhat test --bail --no-compile test/unit/circuits/transfer-regulator.circom.test.mjs (This is also included in `npm run unit-test-circuits`
- npx hardhat test --bail --no-compile test/kem-dem-regulator.test.mjs (This is also included in `npm run test-general-stuff`
- npm run test-erc20-tokens (To test in real scenario you need to simulate a regulator in start-nightfall with a REGULATOR_URL  `REGULATOR_URL=http://localhost:8080 …
> Update Client Service to enable Regulator for transfers

- nightfall-deployer/contracts/MerkleTree_Stateless.sol
- nightfall-deployer/contracts/mocks/MerkleTree_StatelessMock.sol
- package-lock.json
- package.json
- test/unit/SmartContracts/challenges.unit.test.mjs
- test/unit/SmartContracts/merkleTree.unit.test.mjs
- wallet/package-lock.json
- Fix calculate root in MerkleTree_Stateless library:
1. Use leafCount instead of lastLeafIndex. This parameter is from Utils.getLeafCount(blockL2.packedInfo), and getLeafCount returns the leaf count and not the last leaf index.
2. Init node index according to the leaf count and the frontier slot.
- Test MerkleTree_Stateless library. I created tests for calculateRoot and updateFrontier (I didn't find any bugs in this function). I created MerkleTree_StatelessMock so it will be possible to test this library directly.
As far as I know, there are no open issues on this bug.
`npm run unit-test-merkle_tree` or `npm run unit-test`
> fix: on-chain root calculation

- nightfall-deployer/entrypoint.sh
- nightfall-deployer/src/index.mjs
Executes the "trusted setup" process in-parallel to the "smart contracts deployment"(compilation + migrations) process which reduces system bootstap (`./bin/start-nightfall` / `docker-compose up`) time by up to 2 minutes (on local dev machines and ci agents alike). Executes 'truffle' commands via a "promisified" shell.
Executes the contracts setup (transfer of ownership and so) after both "trusted setup" and "smart contracts deployment" are concluded. Failure of any of the aforementioned stages should fail the entire bootsrap process.
There has been a relevant inline "[TODO](https://github.com/EYBlockchain/nightfall_3/blob/ece2c9400ca473417e8144b861c4b66054db71ce/nightfall-deployer/src/index.mjs#L6)" but not an issue.
- Build the core nf3 components via …
> Parallelize trusted setup and contracts deployment

- .github/workflows/on-pull-request-master.yml
- docker/admin.Dockerfile
- docker/challenger.Dockerfile
- docker/circom.Dockerfile
- docker/client.Dockerfile
- docker/deployer.Dockerfile
- docker/hosted-utils-api-server.Dockerfile
- docker/optimist.Dockerfile
- docker/optimist.standalone.Dockerfile
- docker/proposer.Dockerfile
- docker/worker.Dockerfile
Trying to both improve container images build time on dev machines and on CI and produce lean images 
which is beneficial for both security (reduced attack surface) and performance.
- In contrast to Docker Desktop distributions, in this linux CI runner we have to opt-in to leverage the newer,
more performant and feature-rich [Buildkit](https://docs.docker.com/build/buildkit/) by setting environment variable `DOCKER_BUILDKIT=1`. This allows leverging buildkit while using `docker-compose`/ docker CLI in shell scripts. 
This change alone reduces the images build time by about 1.5-2 minutes (varies per ci job).
- Prefering the "slim" variants of rust/node base images which is applicable and only requires installing relevant packages such as 'git' for the circom and 'python3', 'make' and 'g++' …
> Optimize container images build

- nightfall-deployer/migrations/2_deploy_upgradeable.js
- nightfall-deployer/migrations/3_test_tokens_migration.js
To remove restrictions on deposits and withdrawals, we typically set a value of `-1` on the restriction amount (it needs to be negative). However, since we divide the restricted amount by 4, the result is a `0` effectively preventing any deposit. 
No
> fix: fixing unrestricted deposits

- nightfall-deployer/entrypoint.sh
- nightfall-deployer/src/index.mjs
Im having some issues with the parallelization of deployment of circuits and contracts. It fails about 50% of the time when it never failed earlier. So, im allowing for an option to go to the old way. Default deployment is parallel. If you want serial deployment, define env `PARALLEL_SETUP=false`
As a side note, parallel deployment did not include the address of the deployed erc20 Mock token in the generated metadata
No
> feat: allow serial circuit setup

- .github/workflows/on-pull-request-master.yml
As per GitHub announcement from September 22, 2022, [GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). This PR updates outdated action to the latest version, that runs on top of node.js v16 and removes deprecation warning.
> Fix: update GitHub action and remove deprecation warnings about node v12

- .solcover.js
- package-lock.json
- package.json
- Exclude `Migrations.sol` from Solidity code coverage measurements
- Exclude `mocks` directory from Solidity code coverage measurements 
- Include `Poseidon.sol` and `MerkleTree_Stateless.sol` in Solidity code coverage measurements 
(enabled by updating `solidity-coverage` and `@solidity-parser/parser`)
Nope
`npm ci`
`npx hardhat clean && npx hardhat coverage`
all unit test should run successfully and Solidity code coverage metrics should be printed (and exported to file)
Nope
> Configure solcover (Solidity Coverage)

- nightfall-deployer/contracts/Challenges.sol
- nightfall-optimist/src/services/challenges.mjs
- test/adversary.test.mjs
- test/unit/SmartContracts/challenges.unit.test.mjs
This is a bug fix.  The 'historic root block number not correct' challenge is not salted.  This means that if the challenge commitment is front-run, the original challenger would be locked out from sending a new commitment because they could not generate a new commit hash by changing their salt.
No
There is no change to the standard tests.
> fix: add salt to challenge

- nightfall-client/src/utils/submitTransaction.mjs
Currently, when we submit transactions directly, we send the transaction to all proposers and await for them all to respond. It's good to send the transaction to all proposers to maximise the probability of it being incorporated into a block quickly.  However the `Promise.all` construction means that if any of these requests fail (perhaps a proposer was unreachable) then the whole submission process throws, and that may mean, depending on when the promise rejects, that fewer proposers receive our transaction or, in the worst case, none of them receive it, even if only one proposer was down.
We can fix that by using `Promise.any` this will make the await resolve as soon as one of the proposers receives the transaction.  At that point we can continue on, others may also receive the …
> fix: do not throw if a proposer fails to respond

- nightfall-client/src/routes/burn.mjs
- nightfall-client/src/routes/deposit.mjs
- nightfall-client/src/routes/tokenise.mjs
- nightfall-client/src/routes/transfer.mjs
- nightfall-client/src/routes/withdraw.mjs
- test/e2e/tokens/erc1155.test.mjs
- test/e2e/tokens/erc20.test.mjs
- test/e2e/tokens/erc721.test.mjs
This PR do a small refactor nightfall-client api routes.
some routes were explicitly doing response send via res.json event though error object is passed to common error handler middleware in `common-files/utils/httputils.mjs` file.
which will cause error such as response is already send, also sever logic written in common error handler would not have worked for these APIs
> (nightfall-client) removes res.json for error case

- .eslintignore
- .gitignore
- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/services/database.mjs
- nightfall-optimist/src/event-handlers/block-proposed.mjs
- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- nightfall-optimist/src/services/database.mjs
- test/adversary/transpile-optimist-adversary.mjs
When a duplicate transaction is received, it can, under certain circumstances, overwrite the earlier example of the duplicate in the database. This results in the duplicate transaction not being detected.
No
Conventional `npm test` is fine. The logs of the optimist-resync test will now show a correct resync of block 7, which contains the last-created deposit transaction.  Previously it did not.
> fix transaction save

- config/default.js
- nightfall-client/src/services/process-calldata.mjs
- nightfall-client/src/services/state-sync.mjs
- nightfall-optimist/src/event-handlers/transaction-submitted.mjs
- nightfall-optimist/src/services/state-sync.mjs
When Nightfall attempts to sync, the Blockchain node's websocket frame size may cause problems.  This fix increases the framesize substantially in the web3js client, which should avoid the problem.
It's not really a bug but this PR also updates error logging to explicitly point out if any transaction retrieved from the blockchain is `null`. This can happen because some blockchain nodes do not index older transactions. It's not really a Nightfall bug, more of a blockchain-node setup issue. This change makes it easier for a developer to work out what the issue may be.
> Nightfall may fail to sync when the blockchain history is large

- config/default.js
- nightfall-client/src/event-handlers/block-proposed.mjs
- nightfall-client/src/utils/dataPublisher.mjs
This PR adds a `DataPublisher` utility class to the nightfall client, that is used to publish L2 block data to external services via webhook. This is enabled via the environment variable `CALL_WEBHOOK_ON_CONFIRMATION`. The url of the webhook is configurable via the environment variable `WEBHOOK_PATH`.
The `DataPublisher` supports multiple destinations(webhook for now, could be different transport mechanisms in future like grpc or socket), including multiple webhook destinations for fallback/backup.
The `PayloadSigner` class abstracts away the optional signing of the payload using HMAC. The signing key(secret) is configurable via the environment variable `WEBHOOK_SIGNING_KEY`.
The `RetryHandler` class abstracts away the retry mechanism with exponential backoff strategy that is configurable …
> Publish block data to external services via webhooks
