EYBlockchain/nightfall_3

.github/workflows/check-PRs.yml
start-nightfall

script updated to remove volume only if exist

---

test/http.mjs

The current withdrawBond tests fail with a Geth backend because they require a time-jump forward 1 week and don't pick up on Geth error messages, which are different from Ganache's. This PR wrappers the tests with a Geth/Ganache check and takes appropriate action.

fix: geth now avoids the time-jump in the withdrawBond tests

---

.github/workflows/check-PRs.yml

github actions workflow updated to test for geth as well

---

nightfall-client/Dockerfile
nightfall-optimist/Dockerfile

this PR fixes client and optimist service `docker build`. error description at https://github.com/nodesource/distributions/issues/1266

fixes error curl installation of nodejs

---

test/neg-http.mjs

this PR fixes github action workflow of infura deployment and integration test run, sometime neg-http.mjs challenges test fails

pending fixes neg-http.mjs integration test for infura

---

wallet/README.md

Instructions added to get the tests running on a Mac.

docs: added Mac instructions

---

.github/workflows/check-PRs.yml
.github/workflows/infura-ropsten-deploy-cron-job.yml
test/http.mjs
test/neg-http.mjs
test/utils.mjs

this PR create a workflow which will tigger at the end of every day `cron: "0 0 * * *"`. This workflow take the latest master and deploy to infura ropsten and then integration test
fixes #270

github workflow cron job for infura ropsten deployment and integration test run

---

doc/chain-reorgs.md

fixes #207
fixes #208
fixes #209
This PR adds documentation that explains the situation where a chain reorganisation happens while a rollback has occured on only one branch of a chain fork.  It argues that existing chain-reorg code, together with removal and replaying of events, successfully copes with this corner case.  Assuming the argument to be correct, there is no need to add rollback specific code.  Hence those issues are closed.
The correctness of the argument should be tested by adding rollback to the chain-reorg test coverage (issue #143)

docs: added chain-reorg-with-rollback case

---

.github/workflows/publish-docker-images.yml

Not the biggest PR I've ever made...
Prevents reference format error since our image url is `eyblockchain/nightfall3-client`, not `eyblockchain//nightfall3-client`!

fix: typo in actions file

---

wallet/src/views/transactions/components/header-menu/account-settings.view.jsx
wallet/src/views/transactions/components/transactions/transactions-modal.view.jsx

wallet input validation added 

---

cli/lib/nf3.mjs
common-files/utils/event-queue.mjs
nightfall-optimist/src/event-handlers/block-proposed.mjs
nightfall-optimist/src/event-handlers/new-current-proposer.mjs
nightfall-optimist/src/event-handlers/rollback.mjs
nightfall-optimist/src/index.mjs
nightfall-optimist/src/services/block-assembler.mjs
nightfall-optimist/src/services/database.mjs
test/e2e/nightfall-sdk.test.mjs
test/neg-http.mjs
test/rollback-resync.test.mjs
test/tx-gas.mjs

Review Check PR sdk tests that now are failing or missing functionallity:
- test-e2e. Review different parts now are failing. `npm run test-e2e` to test.
- test-gas. Now reports the cost of a deposit transaction and the cost of a proposeBlock call, which is the value of most interest for comparing performance with other L2 approaches. This was being added through sdk. `npm run test-gas` to test.
In fact, the tests are validated in the Check PR action of this PR.
NOTE: it may be necessary to prune docker volumes

daveroga/review Check PR sdk tests

---

.github/workflows/check-PRs.yml

Remove e2e test from PR Checks for now and it will be added after some pending PRs and fix pending

daveroga/remove e2e from PR Checks

---

wallet/craco.config.js
wallet/src/nightfall-browser/services/deposit.js
wallet/src/nightfall-browser/utils/parseConfigs.js

(nightfall-browser) BigInt config deserialised 

---

cli/lib/index.mjs
wallet/src/common-files/utils/contract.js
wallet/src/store/transactions/transactions.thunks.js

for deposit, approve and submitTransaction dependency to cli removed, and instead implemented web3.js for wallet
fixes #421

nightfall_browser - web3.js used for approve and submitTransaction 

---

nightfall-optimist/src/services/state-sync.mjs

fix: corrected empty blockchain check

---

cli/lib/nf3.mjs
wallet/src/views/wallet/index.jsx
wallet/test/constants.py
wallet/test/helpers/wallet.py
wallet/test/wallet_test.py

Add automatic login to wallet tests

feat: add login to wallet tests

---

wallet/src/common-files/utils/contract.js
wallet/src/common-files/utils/web3.js
wallet/src/store/transactions/transactions.thunks.js
wallet/src/views/bridge/index.jsx

this PR fixes and few code
1. web3 connect to metamask provider
2. get account to metamask connect for submitTransaction as well for approve
3. through out the code global object `window` is referred as `global`

(nightfall_browser) fixes web3js to use provider from MetaMask

---

.github/workflows/check-PRs.yml

[Removed wallet test from github actions until we have the ocmplete flow (proving keys) right

fix: remove github actions tests

---

cli/lib/nf3.mjs
nightfall-optimist/src/app.mjs
nightfall-optimist/src/routes/contract-address.mjs
nightfall-optimist/src/routes/index.mjs

Fix issue #461 
Resolution:
- Add endpoint /contract-address to optimist 
- SDK add getContractAddressOptimist

daveroga/Add contract-address endpoint in optimist

---

.github/workflows/ropsten-deploy-cron-job.yml
wallet/package-lock.json
wallet/package.json

this PR also fix a eslint bug from master

github action updated ropsten cronjob on every monday

---

config/default.js
doc/mpc.md
docker-compose.dev.yml
docker-compose.yml
start-nightfall
zokrates-worker/.gitignore
zokrates-worker/package-lock.json
zokrates-worker/package.json
zokrates-worker/src/index.mjs
zokrates-worker/src/mpc.sh
zokrates-worker/src/services/generateKeys.mjs
zokrates-worker/src/zokrates-lib/beacon.mjs
zokrates-worker/src/zokrates-lib/ceremony.mjs
zokrates-worker/src/zokrates-lib/contribution.mjs
zokrates-worker/src/zokrates-lib/exportKeys.mjs
zokrates-worker/src/zokrates-lib/index.mjs
zokrates-worker/src/zokrates-lib/setup.mjs

I can't commit the radix files because they're over 500mb in size. We'll think of a different solution. In the meantime I'm creating this PR so we can see the diff.
Closes #282

feat: completing the MPC ceremony 🙏

---

wallet/src/hooks/User/index.jsx

(nightfall-browser) bug fixed - websocket initiating at all page

---

config/default.js
test/ping-pong/docker-compose.host.docker.internal.yml
test/ping-pong/docker-compose.ropsten.yml
test/ping-pong/user-local/src/index.mjs

Fixes #622 
- Fix `recipients.user1` with `pkds.user1`.
- Fix variables in user docker file that were not used in ping pong test.
- Fix values in user docker file variables for the test to work.

Ping pong test reference recipients.user1 that doesn't exist

---

cli/lib/nf3.mjs
nightfall-optimist/src/event-handlers/subscribe.mjs

WS logs are cluttering proposer logs and makes debugging harder. I have removed those

remove ws ping logs

---

wallet/config/paths.js
wallet/config/webpack.config.js
wallet/package.json
wallet/public/app_loader.js
wallet/public/integration.html

This PR finalises the integration into the polygon browser.

web integration

---

config/default.js

Add network configuration for ganache AWS (staging)

add params for aws ganache

---

nightfall-optimist/src/event-handlers/transaction-submitted.mjs

Handle nonexistent transaction case

fix: fix optmist state resync

---

nightfall-deployer/contracts/Shield.sol

This adds a couple of require statements that revert with a message if:
1) the ERC20 `transferFrom` returns false;
2) the maximum amount restriction is zero.
I think that's all that can be added.

add more debug to shield

---

nightfall-deployer/contracts/Challenges.sol

Historic root challenges need to be the inverse of what we currently have

fix: challenge historic root

---

nightfall-deployer/contracts/Proposers.sol
nightfall-deployer/contracts/Shield.sol
nightfall-deployer/contracts/State.sol
nightfall-deployer/migrations/2_deploy_upgradeable.js

Fixes some missing contract initialisations. They're not significant now but could become a security issue in the future, so best to fix them.

initialise contracts

---

package.json

I pushed an incorrect lint script in packag.json by mistake. This PR reverts that change

fix: fix error in package.json

---

nightfall-deployer/contracts/Utils.sol

This PR updates some issues with the on-chain hashing of `hashTransactionHashes`. The issue arose because the initial hashing of the dynamic array assumed the memory layout contained zero bytes after the `leaves` data.
This isn't guaranteed, so we now instead copy the `transactionsHashes` into a structure beginning at the canonical zero pointer. Batching does not seem to be needed as we don't run into stack issues even when hashing 32 transactions.

Correct on-chain merkle hashing

---

.github/workflows/check-PRs.yml
common-files/utils/contract.mjs
config/default.js
docker-compose.standalone.geth.yml
test/adversary.test.mjs

Update RETRIES in waitForContract because in `geth` sometimes it takes longer to deploy contracts and github actions are not passing because timeout.

Fix adversary test error

---

config/default.js

Added some configurability to MULTISIG variables for ease of deployment

fix: adapt config for real deployment

---

client.Dockerfile

Fixes: #830 
Getting error when building the client image in Mac M1.

Mac m1 client fix

---

nightfall-deployer/migrations/2_deploy_upgradeable.js

Fixes typo when setting token restrictions

fix: error when setting token restrictions

---

cli/package-lock.json
cli/package.json
common-files/package-lock.json
nightfall-client/package-lock.json
nightfall-client/package.json
nightfall-deployer/package-lock.json
nightfall-deployer/package.json
nightfall-optimist/package-lock.json
nightfall-optimist/package.json
nightfall-optimist/src/app.mjs
zokrates-worker/package-lock.json
zokrates-worker/package.json
zokrates-worker/src/app.mjs

this PR fixes security vulnerability

fix security vulnerability

---

wallet/package-lock.json
wallet/src/nightfall-browser/services/fetch-circuit.js
wallet/src/static/supported-token-lists/supported-tokens-local.ts
zokrates-worker/src/zokrates-lib/compile.mjs

this PR does a small refactor,  at time localrun out/program file and circuit abi.json file are now fetched locally instead frrom aws s3 bucket

(wallet/nightfall bowser) refactor fetch circuits files

---

.github/workflows/check-PRs.yml
optimist.Dockerfile
setup-nightfall
wallet/package-lock.json
wallet/package.json
wallet/src/components/SideBar/sideItem.jsx
wallet/src/components/Transactions/index.jsx
wallet/src/nightfall-browser/services/fetch-circuit.js
wallet/src/static/supported-token-lists/supported-tokens-local.ts
wallet/src/utils/lib/local-storage.js
worker.Dockerfile
zokrates-worker/src/zokrates-lib/compile.mjs
zokrates.Dockerfile

this PR upgrade  zokrates version from 0.7.10 to 0.7.13.
also do a small refactor to zokrates.Dockerfile

zokrates upgraded to 0.7.13

---

test/e2e/gas.test.mjs

Use makeBlockNow() + waitForEvent('block proposed') instead of emptyL2.

fix: gas test

---

nightfall-client/src/services/transfer.mjs
nightfall-client/src/services/withdraw.mjs
nightfall-client/src/utils/getCommitmentInfo.mjs
wallet/src/nightfall-browser/utils/getCommitmentInfo.ts

Adding some logs and fixing a wrong comparison between numbers and bigInt to fix the restriction withdrawal test

Fix restriction withdrawal test

---

nightfall-optimist/src/services/transaction-checker.mjs

Fixing a wrong error code for transaction error

transaction error code fix

---

test/e2e/tokens/erc20.test.mjs
test/utils.mjs

Improving erc20 circuit test using circuits flexibility

Improving erc20 circuit test

---

doc/mythril.md
doc/slither.md

fixes #880 
Having considered the results of the Mythril and Slither static analysis, I do not believe that we need to make any updates to our smart contract code as a result. My reasoning is captured in comments in #880 and also in documents attached to this PR [here](https://github.com/EYBlockchain/nightfall_3/blob/westlad/static-analysis/doc/mythril.md) and [here](https://github.com/EYBlockchain/nightfall_3/blob/westlad/static-analysis/doc/slither.md).  These are the original reports which I have annotated with the actions to be taken, with reasons (search for `Action Taken` in the first document  and check annotations in the summary for the second document).

results of static analysis

---

config/default.js
wallet/src/static/supported-token-lists/supported-tokens-testnet.ts

Quick changes, we need to support another token on Goerli, stMATIC, so LIDO can proceed with their integration

Supporting stMATIC

---

nightfall-deployer/contracts/Challenges.sol
nightfall-deployer/contracts/Utils.sol
nightfall-optimist/src/services/challenges.mjs
nightfall-optimist/src/services/transaction-checker.mjs
start-nightfall
test/adversary/adversary-code/block.mjs
test/adversary/adversary-code/database.mjs

this PR add adversary code to create historicError type transaction.
also update proofVerification  challenge in challenge.sol
fixes #https://github.com/EYBlockchain/nightfall_3_private/issues/206

add historic root error case for proof verification challenge

---

nightfall-optimist/src/event-handlers/block-proposed.mjs

Feat: #920 
Add timeBlockL2 in invalidblock for the Block Explorer.

Add timeBlockL2 to invalidblock

---

.github/workflows/check-PRs.yml
docker-compose.apps.yml
proposer.Dockerfile
setup-nightfall

Adding proposer liveliness tests

---

nightfall-client/src/routes/deposit.mjs
nightfall-client/src/routes/transfer.mjs
nightfall-client/src/routes/withdraw.mjs

prevent logging secret information in client when doing deposit, transfer and withdraw

remove privateKeys when logging

---

nightfall-administrator/src/services/contract-transactions.mjs

fix: Administrator ownable contracts transfer ownership

---

nightfall-deployer/contracts/Verifier.sol
nightfall-deployer/migrations/2_deploy_upgradeable.js
nightfall-deployer/migrations/4_upgrade_upgradeable.js

fix: upgrade contracts script missing updates

---

nightfall-client/src/services/commitment-storage.mjs
nightfall-client/src/services/database.mjs
nightfall-optimist/src/services/database.mjs
wallet/src/nightfall-browser/services/database.js

Removing functions that were never called from the database files

Removing Unused functions from database files

---

.github/workflows/check-PRs.yml
test/adversary/adversary-code/database.mjs

This PR fixes a small bug arise in branch `chait/adversary2` after rebase from master.
Also, this PR adds back github action workflow to test adversary-test removed in master
temporary workflow run on this PR (https://github.com/EYBlockchain/nightfall_3/actions/runs/3127552006/jobs/5074300394)
evidence all workflow is passing on this branch

a small bug fix after rebase from master (base branch: chait/adversary2)

---

.github/PULL_REQUEST_TEMPLATE.md

It changes the PR template from `Any relevant logs, error output, etc?` to `What commands can I run to test the change?`.
I think this is a more useful question.
No, this is based on discussion with @imagobea. We thought the current phrasing is a bit confusing.
^^^ 
No

clarify question in PR template

---

config/default.js
nightfall-client/src/services/finalise-withdrawal.mjs
nightfall-client/src/services/process-calldata.mjs
nightfall-deployer/contracts/Challenges.sol
nightfall-deployer/contracts/ChallengesUtil.sol
nightfall-deployer/contracts/MerkleTree_Stateless.sol
nightfall-deployer/contracts/State.sol
nightfall-deployer/contracts/Structures.sol
nightfall-deployer/contracts/Utils.sol
nightfall-optimist/src/classes/block.mjs
nightfall-optimist/src/routes/proposer.mjs
nightfall-optimist/src/services/block-utils.mjs
nightfall-optimist/src/services/challenges.mjs
nightfall-optimist/src/services/check-block.mjs
nightfall-optimist/src/services/process-calldata.mjs
nightfall-optimist/src/services/state-sync.mjs
wallet/src/nightfall-browser/services/finalise-withdrawal.js

This PR optimizes the gas used for challenging a new root.
To a better understanding of the changes done in this PR we need to take into account the following:
- All challenges have a first part that verifies that the challenger info is valid (so he isn't "cheating") and then the actual challenge. In this case, what the test was doing was inserting all the leaves to calculate the root of the previous block to make sure that the info provided is valid and then do the same with the current block to perform the challenge. 
- Timber merkle trees have the following property: if you have the updated frontier and the leafIndex of the last leaf, you are able to calculate the root. This means that the process can be split in two: adding all the leaves (which updates the frontier) and calculate the …

Optimizing Root Challenge

---

setup-nightfall

Fixes a bug in the setup script which prevents it running on an M1 Mac.
It's essentially a small typo

fix: typos in script

---

apps/challenger/src/challenger.mjs
nightfall-deployer/src/contract-setup.mjs

Fixes needed for deployment to AWS:
- Correct path to `common-files` in challenger
- Contract transfer fails when deploying to geth as if multiple transactions share same nonce. I attempted to serialize calls and this seems to work fine.
No
Any test that relies on correct smart contract deployment
No

Several deployment fixes

---

common-files/package.json

This PR adds necessary changes for common-files to work as a npm module [https://www.npmjs.com/package/@polygon-nightfall/common-files](https://www.npmjs.com/package/@polygon-nightfall/common-files).
#913

Convert common-files to npm module and add scope @polygon-nightfall

---

.github/workflows/check-PRs.yml
doc/how_it_works.md
doc/pos.md
nightfall-deployer/contracts/Challenges.sol
nightfall-deployer/contracts/Config.sol
nightfall-deployer/contracts/Proposers.sol
nightfall-deployer/contracts/Shield.sol
nightfall-deployer/contracts/State.sol
test/multisig/administrator.test.mjs
test/multisig/nightfall-multisig.mjs

Feat: #1018 
- Update parameters PoS.
- When `maxProposer=1` limit the proposer to bootProposer.
- Update documentation in `/doc` folder about proposer PoS.
- Some multisig fixes.
Issue #1018 
npm run test-administrator
No

Add methods update parameters PoS

---

test/multisig/administrator.test.mjs

Controls if aws and doesn't register/deregister the first proposer.
No
npm run test-administrator
No

Small fix admin test for aws

---

common-files/utils/httputils.mjs
docker/docker-compose.client.dev.yml
docker/docker-compose.client.yml
zokrates-worker/src/index.mjs

It fix the missing MongoDB service required by the client service.
No
`./setup-nightfall && cd nightfall-client && ./start-client`
No

Adding Mongodb service to client's docker-compose

---

.gitignore

Fixes a small typo in the gitignore file

.gitignore typo fix

---

apps/challenger/package-lock.json
apps/challenger/package.json
apps/proposer/package-lock.json
apps/proposer/package.json
apps/synchronizer/package-lock.json
apps/synchronizer/package.json
cli/package-lock.json
cli/package.json
common-files/package-lock.json
common-files/package.json
nightfall-administrator/package-lock.json
nightfall-administrator/package.json
nightfall-client/package-lock.json
nightfall-client/package.json
nightfall-deployer/package-lock.json
nightfall-deployer/package.json
nightfall-optimist/package-lock.json
nightfall-optimist/package.json
package-lock.json
package.json
zokrates-worker/package-lock.json
zokrates-worker/package.json

Updates `@polygon-nightfall/common-files` to `0.0.5`.
#1089 
This is one off. In the future it is going to be automated.

Upgrade @polygon-nighfall/common-files to 0.0.5 across the packages

---

cli/lib/nf3.mjs
nightfall-client/src/services/tokenise.mjs
nightfall-deployer/circuits/tokenise.zok
test/e2e/tokens/l2tokenisation.test.mjs

Add support for values in tokenise, change some parameter ordering, some comments
`npm run test-l2tokenisation`

feat: update tokenise to use value

---

.github/workflows/on-pull-request-master.yml
bin/start-nightfall
docker/admin.Dockerfile
docker/client.Dockerfile
docker/deployer.Dockerfile
docker/optimist.Dockerfile
docker/optimist.standalone.Dockerfile
docker/proposer.Dockerfile
docker/worker.Dockerfile

This MR fix common-files linking inside Docker containers. Very good spot @israelboudoux thank you for collaboration.

Fix common-files linking inside containers

---

hosted-utils-api-server/entrypoint.sh
package.json
wallet/config/webpack.config.js
wallet/package-lock.json
wallet/package.json
wallet/public/index.html
wallet/src/common-files/utils/crypto/poseidon/poseidon.js
wallet/src/hooks/User/index.jsx
wallet/src/nightfall-browser/services/kem-dem.ts
wallet/src/nightfall-browser/services/keys.ts
wallet/src/utils/pricingAPI.ts

- fix hosted utils api entrypoint script to generate a valid JSON
- adds prune npm script on the top level package.json file
- wallet now uses common-files from npm module
- removes references to empty scripts in wallet
- fixes poseidon hash function in wallet
- fixes wallet sync
- #1126
- #1127 
- `npm run start:testnet` in wallet package

Wallet sync fix

---

.github/workflows/on-push-master.yml
apps/challenger/package-lock.json
apps/challenger/package.json
apps/proposer/package-lock.json
apps/proposer/package.json
apps/synchronizer/package-lock.json
apps/synchronizer/package.json
cli/package-lock.json
cli/package.json
common-files/package-lock.json
common-files/package.json
nightfall-administrator/package-lock.json
nightfall-administrator/package.json
nightfall-client/package-lock.json
nightfall-client/package.json
nightfall-deployer/package-lock.json
nightfall-deployer/package.json
nightfall-optimist/package-lock.json
nightfall-optimist/package.json
package.json
zokrates-worker/package-lock.json
zokrates-worker/package.json

It changes the `on-pull-request-master` workflow to push `common-files/package.json` changes to the base branch when a change in this file is detected.
No
No, only after merging it is possible to verify the outcome.
The option `Read and write permissions` on the _Workflow_ section should be selected on the page https://github.com/EYBlockchain/nightfall_3/settings/actions.

Patching common-files/package.json

---

package-lock.json
package.json
test/e2e/protocol/health-and-contracts.test.mjs

Updates `nightfall-sdk` package vs, updates test suite.
No
```
npm run test-e2e-protocol
```
N/a

chore: update nightfall-sdk and tests

---

wallet/package.json
wallet/public/app_loader.js

This PR updates remote URL for wallet. This part is needed to deployment.
#1145 
`npm run deploy`

Update wallet remote url

---

wallet/package-lock.json
wallet/package.json
wallet/src/nightfall-browser/services/commitment-storage.js
wallet/src/nightfall-browser/services/deposit.js
wallet/src/nightfall-browser/services/transfer.js
wallet/src/nightfall-browser/services/withdraw.js
wallet/src/nightfall-browser/utils/compute-witness.ts
wallet/src/static/supported-token-lists/supported-tokens-local.ts

Fixes issues with running the wallet.
1) start nightfall
2) start a proposer app
3) run the wallet locally
4) Perform operations in an open browser

Fixes for wallet

---

wallet/package.json

Adds handy scripts to testnet deployment to wallet package.
🙅‍♂️
`npm run deploy:testnet`
Have a lovely day y'all 🤗

feat: add deploy to testnet scripts to wallet package

---

wallet/src/common-files/utils/curve-maths/curves.js
wallet/src/nightfall-browser/services/deposit.js
wallet/src/nightfall-browser/services/transfer.js
wallet/src/nightfall-browser/services/withdraw.js

Circom operations using indexedDB stored circuits and keys

fix: wallet operations

---

test/unit/SmartContracts/state.unit.test.mjs

Uses the function `getMinimumStake` and `getValuePerSlot` so as not to cause problems on any changes to the configuration values in `config.sol`
npm run unit-test-state

Fix state unit test

---

nightfall-deployer/contracts/Challenges.sol
package.json
test/unit/SmartContracts/challenges.unit.test.mjs
test/unit/SmartContracts/state.unit.test.mjs
test/unit/utils/utils.mjs

What does this implement/fix? Explain your changes.
This PR adds unit tests for the Challenges.sol smart contract
Does this close any currently open issues?
#1139 
What commands can I run to test the change?
npm run unit-test-challenges

Challenges contract unit test

---

.github/workflows/on-pull-request-master.yml
test/e2e/tokens/erc1155.test.mjs
test/e2e/tokens/erc20.test.mjs
test/e2e/tokens/erc721.test.mjs

this PR refactor test files (such as `erc1155.test.mjs` , `erc20.test.mjs` and `erc721.test.mjs`) to look for any rollback and fail test if found
fixes # https://github.com/EYBlockchain/nightfall_3_private/issues/249

good test now count rollback counts

---

.github/workflows/on-pull-request-master.yml

fix: reduce gas-test

---

wallet/src/contract-abis/Shield.json
wallet/src/nightfall-browser/classes/commitment.js
wallet/src/nightfall-browser/utils/computeCircuitInputs.ts

Update Shield.json and small fix to make the wallet work

Wallet fix

---

README.md
config/default.js
docker/docker-compose.ganache.yml
docker/docker-compose.multiproposer-test.yml
example.multiproposer-test.env
test/ping-pong/index.mjs
test/ping-pong/ping-pong.test.mjs

After rebasing getting some errors 
- Fix ping pong rotateProposerBlocks
- Fix config duplicate variable for the same purpose
No
- ./bin/start-multiproposer-test-env -g
- npm run ping-pong
No

Fix ping pong and config

---

nightfall-client/src/index.mjs
nightfall-deployer/src/circuit-setup.mjs

- Client : ensure client doesnt process any events while syncing
- Deployer: fixed typo

Client and deployer issues

---

.github/workflows/on-pull-request-master.yml
apps/challenger/config/default.js
apps/challenger/docker-entrypoint.sh
apps/proposer/config/default.js
apps/proposer/docker-entrypoint.sh
docker/challenger.Dockerfile
docker/docker-compose.multiproposer-test.yml
example.multiproposer-test.env
test/ping-pong/index.mjs
test/ping-pong/ping-pong.test.mjs

- Add withdraw to ping pong, so we have deposit, transfer and withdraw covered.
- Add in local for the docker-compose a lazy optimist , a bad client and a challenger.
- Update the test to produce only good blocks and good transactions by default but have options to parameterize to produce bad transactions by the bad clien.
Yes. #1288.
- ./bin/start-multiproposer-test-env -g
- npm run ping pong
You can test with this `multiproposer-test.env` in the root folder:
```
export CLIENT1_API_URL=http://localhost:8083
export CLIENT2_API_URL=http://localhost:8086
export CLIENT2_TX_TYPES_SEQUENCE="ValidTransaction,IncorrectInput,ValidTransaction"
export USER1_KEY=0x4775af73d6dc84a0ae76f8726bda4b9ecf187c377229cb39e1afa7a18236a69e
export USER2_KEY=0xd42905d0582c476c4b74757be6576ec323d715a0c7dcff231b6348 …
```

Add withdraw, lazy optimist, bad client to ping pong

---

.github/workflows/on-pull-request-master.yml
common-files/classes/proof.mjs
common-files/classes/transaction.mjs
common-files/utils/curve-maths/curves.mjs
nightfall-client/src/services/burn.mjs
nightfall-client/src/services/deposit.mjs
nightfall-client/src/services/tokenise.mjs
nightfall-client/src/services/transfer.mjs
nightfall-client/src/services/withdraw.mjs
nightfall-deployer/contracts/Challenges.sol
nightfall-optimist/src/services/transaction-checker.mjs
wallet/src/common-files/classes/transaction.js
wallet/src/nightfall-browser/services/deposit.js
wallet/src/nightfall-browser/services/transfer.js
wallet/src/nightfall-browser/services/withdraw.js

Challenge fix

---

docker/docker-compose.dev.yml

It fixes the issues with nodemon auto refresh.

Fix nodemon auto refresh on dev env

---

README.md

Include in README.md that you should build adversary to run ping pong test
No
No

fix readme build adversary for ping pong test

---

README.md
apps/proposer/src/proposer.mjs
cli/lib/nf3.mjs
config/default.js
hosted-utils-api-server/package.json
wallet/.template.copy.env

Updates for AWS deployment
- Proposer periodically checks if its part of registered set and re-registers it not
- Add try/catch in nf3 challenger emitter
- Add X509 config to all network types
- Dev mode in hosted-utils
No

AWS deployment

---

nightfall-deployer/contracts/Proposers.sol
nightfall-optimist/src/index.mjs
nightfall-optimist/src/services/auto-change-current-proposer.mjs

this pr adds to the nightfall-node the automatic call to the `changeCurrentProposer` by the next proposer 
`./bin/start-multiproposer-test-env -g`

nightfall node autochangecurrentproposer

---

.github/workflows/on-pull-request-master.yml
apps/challenger/src/app.mjs
apps/proposer/src/app.mjs
common-files/utils/utils.mjs
config/default.js
nightfall-deployer/scripts/fund-accounts.mjs
test/adversary.test.mjs
test/circuits.test.mjs
test/e2e/protocol/health-and-contracts.test.mjs
test/e2e/protocol/proposer.test.mjs
test/e2e/tokens/erc1155.test.mjs
test/e2e/tokens/erc20.test.mjs
test/e2e/tokens/erc721.test.mjs
test/e2e/tokens/l2tokenisation.test.mjs
test/gas.test.mjs
test/multisig/administrator.test.mjs
test/optimist-resync.test.mjs
test/ping-pong/ping-pong.test.mjs
test/utils.mjs
test/x509.test.mjs

fixes https://github.com/EYBlockchain/nightfall_3_private/issues/267

remove use process.env.ENVIRONMENTS  across the files

---

nightfall-client/src/services/keys.mjs

This PR update key.mjs of nightfall-client as of the BIP39 implementation of wallet key.ts
fixes #1381

removed hex toString on seed

---

README.md
nightfall-optimist/src/services/transaction-checker.mjs
wallet/package.json
wallet/src/hooks/User/index.jsx

- Adding caching layer to the transaction handler
- Fixing outdated piece of documentation and formatting change
Just by implementing a simple caching layer, I managed to improve a duration of this call by ≈207%. Here are some simple stats captured during the performance audit.
1. 840.654875000008
2. 660.630209000025
3. 664.871458999929
4. 645.341875000042
5. 626.131749999942
6. 581.206667000079
7. 1019.27583400009
8. 664.408999999985
9. 642.822209000005
10. 672.740458999993
**average: 701.80843370001**
1. 365.487208999693
2. 364.226541999728
3. 337.067041998729
4. 327.651541000232
5. 323.26920799911
6. 360.825833000243
7. 335.701917000115
8. 319.334916999564
9. 336.441042000428
10. 315.172040998936
**average: 338.517729199678**
It is generally a good practice to format the code and avoid …

Cache verification key and fees on transaction handler (≈207% call duration improvement)

---

nightfall-deployer/contracts/MerkleTree_Stateless.sol

Recent changes to the MerkleStateless functions fixed an issue with `calculateRoot` but also highlighted some of the unnecessary complexity in the code.
This refactors these functions to behave more like the off-chain timber code: using right-shifts to move up the tree and the parity checks to hash up to the parent (i.e. inverting the current parity logic).
No
The newly added ` npm run unit-test-merkle_tree`
This is a logical refactor

Refactor Merkle stateless functions.

---

common-files/utils/performance-benchmark.mjs

This PR resolves https://github.com/NightfallRollup/nightfall-config/issues/31
How to use:
```js
import PerformanceBenchmark from '@polygon-nightfall/common-files/utils/performance-benchmark.mjs';
// instantiate new PerformanceBenchmark
const performanceBenchmark = new PerformanceBenchmark();
for (let index = 0; index < 2; index++) {
performanceBenchmark.start('a');
console.log(index);
performanceBenchmark.stop('a');
}
for (let index = 0; index < 2; index++) {
performanceBenchmark.start('b');
console.log(index);
performanceBenchmark.stop('b');
}
// log stats for id a
console.log(JSON.stringify(performanceBenchmark.stats('a'), null, 4));
// {
//   "id": "a",
//   "count": 2,
//   "duration": [
//       {
//           "start": 14.356167078018188,
//           "stop": 17.888582944869995,
// …
```

Performance benchmark helper

---

.github/workflows/on-pull-request-master.yml
nightfall-deployer/entrypoint.sh
nightfall-deployer/src/index.mjs

this PR removes parallel execution of contract deploy and circuit setup

remove PARALLEL_SETUP logic in nightfall_deployer

---

doc/adding_certificates.md
doc/commitment_selection.md
doc/in-band-secret-distribution.md
doc/mpc.md
doc/nightfall_node.md

Fix: typos
